#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "ActivesessionGetListV1ResponseMPayload.h"
#import "CommonResponseGetList.h"
#import "CommonResponseObjDebug.h"
#import "CommonResponseObjDebugPayloadGetList.h"
@protocol ActivesessionGetListV1ResponseMPayload;
@class ActivesessionGetListV1ResponseMPayload;
@protocol CommonResponseGetList;
@class CommonResponseGetList;
@protocol CommonResponseObjDebug;
@class CommonResponseObjDebug;
@protocol CommonResponseObjDebugPayloadGetList;
@class CommonResponseObjDebugPayloadGetList;



@protocol ActivesessionGetListV1Response
@end

@interface ActivesessionGetListV1Response : CommonResponseGetList


@property(nonatomic) ActivesessionGetListV1ResponseMPayload* mPayload;

@end
