#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "ActivesessionResponseCompoundApikey.h"
#import "ActivesessionResponseCompoundUser.h"
#import "FieldEActivesessionEzsign.h"
#import "FieldEActivesessionEzsignaccess.h"
#import "FieldEActivesessionEzsignprepaid.h"
#import "FieldEActivesessionOrigin.h"
#import "FieldEActivesessionRealestateinprogress.h"
#import "FieldEActivesessionUsertype.h"
#import "FieldEActivesessionWeekdaystart.h"
#import "FieldESystemconfigurationEzsignofficeplan.h"
#import "FieldEUserEzsignaccess.h"
#import "FieldEUserEzsignprepaid.h"
@protocol ActivesessionResponseCompoundApikey;
@class ActivesessionResponseCompoundApikey;
@protocol ActivesessionResponseCompoundUser;
@class ActivesessionResponseCompoundUser;
@protocol FieldEActivesessionEzsign;
@class FieldEActivesessionEzsign;
@protocol FieldEActivesessionEzsignaccess;
@class FieldEActivesessionEzsignaccess;
@protocol FieldEActivesessionEzsignprepaid;
@class FieldEActivesessionEzsignprepaid;
@protocol FieldEActivesessionOrigin;
@class FieldEActivesessionOrigin;
@protocol FieldEActivesessionRealestateinprogress;
@class FieldEActivesessionRealestateinprogress;
@protocol FieldEActivesessionUsertype;
@class FieldEActivesessionUsertype;
@protocol FieldEActivesessionWeekdaystart;
@class FieldEActivesessionWeekdaystart;
@protocol FieldESystemconfigurationEzsignofficeplan;
@class FieldESystemconfigurationEzsignofficeplan;
@protocol FieldEUserEzsignaccess;
@class FieldEUserEzsignaccess;
@protocol FieldEUserEzsignprepaid;
@class FieldEUserEzsignprepaid;



@protocol ActivesessionResponseCompound
@end

@interface ActivesessionResponseCompound : Object


@property(nonatomic) FieldEActivesessionUsertype* eActivesessionUsertype;

@property(nonatomic) FieldEActivesessionOrigin* eActivesessionOrigin;

@property(nonatomic) FieldEActivesessionWeekdaystart* eActivesessionWeekdaystart;
/* The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English| 
 */
@property(nonatomic) NSNumber* fkiLanguageID;
/* The Name of the Company in the language of the requester 
 */
@property(nonatomic) NSString* sCompanyNameX;
/* The Name of the Department in the language of the requester 
 */
@property(nonatomic) NSString* sDepartmentNameX;
/* Whether the active session is in debug or not 
 */
@property(nonatomic) NSNumber* bActivesessionDebug;
/* Whether the active session is superadmin or not 
 */
@property(nonatomic) NSNumber* bActivesessionIssuperadmin;
/* Can access attachment when we clone a user [optional]
 */
@property(nonatomic) NSNumber* bActivesessionAttachment;
/* Can access canafe when we clone a user [optional]
 */
@property(nonatomic) NSNumber* bActivesessionCanafe;
/* Can access financial element when we clone a user [optional]
 */
@property(nonatomic) NSNumber* bActivesessionFinancial;
/* Can access closed realestate folders when we clone a user [optional]
 */
@property(nonatomic) NSNumber* bActivesessionRealestatecompleted;

@property(nonatomic) FieldEActivesessionEzsign* eActivesessionEzsign;

@property(nonatomic) FieldEActivesessionEzsignaccess* eActivesessionEzsignaccess;

@property(nonatomic) FieldEActivesessionEzsignprepaid* eActivesessionEzsignprepaid;

@property(nonatomic) FieldEActivesessionRealestateinprogress* eActivesessionRealestateinprogress;
/* The customer code assigned to your account 
 */
@property(nonatomic) NSString* pksCustomerCode;
/* The unique ID of the Systemconfigurationtype 
 */
@property(nonatomic) NSNumber* fkiSystemconfigurationtypeID;
/* The unique ID of the Signature [optional]
 */
@property(nonatomic) NSNumber* fkiSignatureID;
/* The unique ID of the Ezsignuser [optional]
 */
@property(nonatomic) NSNumber* fkiEzsignuserID;
/* Whether if Ezsign is paid by the company or not [optional]
 */
@property(nonatomic) NSNumber* bSystemconfigurationEzsignpaidbyoffice;

@property(nonatomic) FieldESystemconfigurationEzsignofficeplan* eSystemconfigurationEzsignofficeplan;

@property(nonatomic) FieldEUserEzsignaccess* eUserEzsignaccess;

@property(nonatomic) FieldEUserEzsignprepaid* eUserEzsignprepaid;
/* Whether the User's eZsign subscription is a trial [optional]
 */
@property(nonatomic) NSNumber* bUserEzsigntrial;
/* The eZsign prepaid expiration date [optional]
 */
@property(nonatomic) NSString* dtUserEzsignprepaidexpiration;
/* An array of permissions granted to the user or api key 
 */
@property(nonatomic) NSArray<NSNumber*>* aPkiPermissionID;

@property(nonatomic) ActivesessionResponseCompoundUser* objUserReal;

@property(nonatomic) ActivesessionResponseCompoundUser* objUserCloned;

@property(nonatomic) ActivesessionResponseCompoundApikey* objApikey;
/* An Array of Registered modules.  These are the modules that are Licensed to be used by the User or the API Key. 
 */
@property(nonatomic) NSArray<NSString*>* aEModuleInternalname;

@end
