#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AgenttypeAutocompleteElementResponse
@end

@interface AgenttypeAutocompleteElementResponse : Object

/* The unique ID of the Agenttype 
 */
@property(nonatomic) NSNumber* pkiAgenttypeID;
/* The name of the Agenttype in the language of the requester 
 */
@property(nonatomic) NSString* sAgenttypeNameX;
/* Whether the Agenttype is active or not 
 */
@property(nonatomic) NSNumber* bAgenttypeIsactive;

@end
