#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "MultilingualApikeyDescription.h"
@protocol MultilingualApikeyDescription;
@class MultilingualApikeyDescription;



@protocol ApikeyRequest
@end

@interface ApikeyRequest : Object

/* The unique ID of the Apikey [optional]
 */
@property(nonatomic) NSNumber* pkiApikeyID;
/* The unique ID of the User 
 */
@property(nonatomic) NSNumber* fkiUserID;

@property(nonatomic) MultilingualApikeyDescription* objApikeyDescription;
/* Whether the apikey is active or not [optional]
 */
@property(nonatomic) NSNumber* bApikeyIsactive;
/* Whether the apikey is signed or not [optional]
 */
@property(nonatomic) NSNumber* bApikeyIssigned;

@end
