#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol BillingentityinternalproductRequest
@end

@interface BillingentityinternalproductRequest : Object

/* The unique ID of the Billingentityinternalproduct [optional]
 */
@property(nonatomic) NSNumber* pkiBillingentityinternalproductID;
/* The unique ID of the Ezmaxproduct 
 */
@property(nonatomic) NSNumber* fkiEzmaxproductID;
/* The unique ID of the Billingentityexternal 
 */
@property(nonatomic) NSNumber* fkiBillingentityexternalID;

@end
