#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "BrandingResponseV3.h"
#import "FieldEBrandingAlignlogo.h"
#import "FieldEBrandingLogo.h"
#import "MultilingualBrandingDescription.h"
@protocol BrandingResponseV3;
@class BrandingResponseV3;
@protocol FieldEBrandingAlignlogo;
@class FieldEBrandingAlignlogo;
@protocol FieldEBrandingLogo;
@class FieldEBrandingLogo;
@protocol MultilingualBrandingDescription;
@class MultilingualBrandingDescription;



@protocol BrandingResponseCompoundV3
@end

@interface BrandingResponseCompoundV3 : BrandingResponseV3

/* The url of the picture used as logo in the Branding [optional]
 */
@property(nonatomic) NSString* sBrandingLogourl;
/* The url of the picture used in email as logo in the Branding [optional]
 */
@property(nonatomic) NSString* sBrandingLogoemailurl;
/* The url of the picture used as logo in the Branding [optional]
 */
@property(nonatomic) NSString* sBrandingLogointerfaceurl;

@end
