#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "BrandingRequestV2.h"
#import "FieldEBrandingAlignlogo.h"
#import "FieldEBrandingLogo.h"
#import "MultilingualBrandingDescription.h"
@protocol BrandingRequestV2;
@class BrandingRequestV2;
@protocol FieldEBrandingAlignlogo;
@class FieldEBrandingAlignlogo;
@protocol FieldEBrandingLogo;
@class FieldEBrandingLogo;
@protocol MultilingualBrandingDescription;
@class MultilingualBrandingDescription;



@protocol BrandingRequestCompoundV2
@end

@interface BrandingRequestCompoundV2 : BrandingRequestV2


@end
