#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldEBrandingLogo.h"
#import "FieldEBrandingLogointerface.h"
#import "MultilingualBrandingDescription.h"
@protocol FieldEBrandingLogo;
@class FieldEBrandingLogo;
@protocol FieldEBrandingLogointerface;
@class FieldEBrandingLogointerface;
@protocol MultilingualBrandingDescription;
@class MultilingualBrandingDescription;



@protocol BrandingResponseCompound
@end

@interface BrandingResponseCompound : Object

/* The unique ID of the Branding 
 */
@property(nonatomic) NSNumber* pkiBrandingID;
/* The unique ID of the Email [optional]
 */
@property(nonatomic) NSNumber* fkiEmailID;

@property(nonatomic) MultilingualBrandingDescription* objBrandingDescription;
/* The Description of the Branding in the language of the requester 
 */
@property(nonatomic) NSString* sBrandingDescriptionX;
/* The name of the Branding  This value will only be set if you wish to overwrite the default name. If you want to keep the default name, leave this property empty [optional]
 */
@property(nonatomic) NSString* sBrandingName;
/* The email address. [optional]
 */
@property(nonatomic) NSString* sEmailAddress;

@property(nonatomic) FieldEBrandingLogo* eBrandingLogo;

@property(nonatomic) FieldEBrandingLogointerface* eBrandingLogointerface;
/* The color of the text. This is a RGB color converted into integer 
 */
@property(nonatomic) NSNumber* iBrandingColortext;
/* The color of the text in the link box. This is a RGB color converted into integer 
 */
@property(nonatomic) NSNumber* iBrandingColortextlinkbox;
/* The color of the text in the button. This is a RGB color converted into integer 
 */
@property(nonatomic) NSNumber* iBrandingColortextbutton;
/* The color of the background. This is a RGB color converted into integer 
 */
@property(nonatomic) NSNumber* iBrandingColorbackground;
/* The color of the background of the button. This is a RGB color converted into integer 
 */
@property(nonatomic) NSNumber* iBrandingColorbackgroundbutton;
/* The color of the background of the small box. This is a RGB color converted into integer 
 */
@property(nonatomic) NSNumber* iBrandingColorbackgroundsmallbox;
/* The color of the interface. This is a RGB color converted into integer [optional]
 */
@property(nonatomic) NSNumber* iBrandingInterfacecolor;
/* Whether the Branding is active or not 
 */
@property(nonatomic) NSNumber* bBrandingIsactive;
/* The url of the picture used as logo in the Branding [optional]
 */
@property(nonatomic) NSString* sBrandingLogourl;
/* The url of the picture used as logo in the Branding [optional]
 */
@property(nonatomic) NSString* sBrandingLogointerfaceurl;

@end
