#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldEBuyercontractRemunerationtype.h"
#import "FieldEBuyercontractStep.h"
#import "FieldEBuyercontractType.h"
@protocol FieldEBuyercontractRemunerationtype;
@class FieldEBuyercontractRemunerationtype;
@protocol FieldEBuyercontractStep;
@class FieldEBuyercontractStep;
@protocol FieldEBuyercontractType;
@class FieldEBuyercontractType;



@protocol BuyercontractResponse
@end

@interface BuyercontractResponse : Object

/* The unique ID of the Buyercontract 
 */
@property(nonatomic) NSNumber* pkiBuyercontractID;
/* The unique ID of the Inscriptiontype 
 */
@property(nonatomic) NSNumber* fkiInscriptiontypeID;

@property(nonatomic) FieldEBuyercontractStep* eBuyercontractStep;
/* The minimum price of the Buyercontract 
 */
@property(nonatomic) NSString* dBuyercontractMinimumprice;
/* The maximum price of the Buyercontract 
 */
@property(nonatomic) NSString* dBuyercontractMaximumprice;

@property(nonatomic) FieldEBuyercontractType* eBuyercontractType;
/* The number of the Buyercontract [optional]
 */
@property(nonatomic) NSString* sBuyercontractContract;
/* The date of the Buyercontract 
 */
@property(nonatomic) NSString* dtBuyercontractDate;
/* The expiration date of the Buyercontract [optional]
 */
@property(nonatomic) NSString* dtBuyercontractExpirationdate;
/* The remuneration of the Buyercontract [optional]
 */
@property(nonatomic) NSString* dBuyercontractRemuneration;

@property(nonatomic) FieldEBuyercontractRemunerationtype* eBuyercontractRemunerationtype;
/* Whether if it's an litigation [optional]
 */
@property(nonatomic) NSNumber* bBuyercontractLitigation;
/* Whether the buyercontract is active or not 
 */
@property(nonatomic) NSNumber* bBuyercontractIsactive;

@end
