#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomCommunicationsenderRequest.h"
#import "FieldECommunicationImportance.h"
#import "FieldECommunicationType.h"
@protocol CustomCommunicationsenderRequest;
@class CustomCommunicationsenderRequest;
@protocol FieldECommunicationImportance;
@class FieldECommunicationImportance;
@protocol FieldECommunicationType;
@class FieldECommunicationType;



@protocol CommunicationRequest
@end

@interface CommunicationRequest : Object

/* The unique ID of the Communication. [optional]
 */
@property(nonatomic) NSNumber* pkiCommunicationID;

@property(nonatomic) FieldECommunicationImportance* eCommunicationImportance;

@property(nonatomic) FieldECommunicationType* eCommunicationType;

@property(nonatomic) CustomCommunicationsenderRequest* objCommunicationsender;
/* The subject of the Communication [optional]
 */
@property(nonatomic) NSString* sCommunicationSubject;
/* The Body of the Communication 
 */
@property(nonatomic) NSString* tCommunicationBody;
/* Whether the Communication is private or not 
 */
@property(nonatomic) NSNumber* bCommunicationPrivate;
/* How the attachment should be included in the email.   Only used if eCommunicationType is **Email** [optional]
 */
@property(nonatomic) NSString* eCommunicationAttachmenttype;
/* The number of days before the attachment link expired.   Only used if eCommunicationType is **Email** and eCommunicationattachmentType is **Link** [optional]
 */
@property(nonatomic) NSNumber* iCommunicationAttachmentlinkexpiration;
/* Whether we ask for a read receipt or not. [optional]
 */
@property(nonatomic) NSNumber* bCommunicationReadreceipt;

@end
