#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AddressResponse.h"
#import "EmailResponse.h"
#import "FieldEContactinformationsType.h"
#import "PhoneResponseCompound.h"
#import "WebsiteResponse.h"
@protocol AddressResponse;
@class AddressResponse;
@protocol EmailResponse;
@class EmailResponse;
@protocol FieldEContactinformationsType;
@class FieldEContactinformationsType;
@protocol PhoneResponseCompound;
@class PhoneResponseCompound;
@protocol WebsiteResponse;
@class WebsiteResponse;



@protocol ContactinformationsResponse
@end

@interface ContactinformationsResponse : Object

/* The unique ID of the Contactinformations 
 */
@property(nonatomic) NSNumber* pkiContactinformationsID;
/* The unique ID of the Address [optional]
 */
@property(nonatomic) NSNumber* fkiAddressIDDefault;
/* The unique ID of the Phone. [optional]
 */
@property(nonatomic) NSNumber* fkiPhoneIDDefault;
/* The unique ID of the Email [optional]
 */
@property(nonatomic) NSNumber* fkiEmailIDDefault;
/* The unique ID of the Website Default [optional]
 */
@property(nonatomic) NSNumber* fkiWebsiteIDDefault;

@property(nonatomic) FieldEContactinformationsType* eContactinformationsType;
/* The url of the Contactinformations [optional]
 */
@property(nonatomic) NSString* sContactinformationsUrl;
/* An Address Object and children to create a complete structure [optional]
 */
@property(nonatomic) AddressResponse* objAddressDefault;

@property(nonatomic) PhoneResponseCompound* objPhoneDefault;
/* An Email Object and children to create a complete structure [optional]
 */
@property(nonatomic) EmailResponse* objEmailDefault;
/* A Website Object and children to create a complete structure [optional]
 */
@property(nonatomic) WebsiteResponse* objWebsiteDefault;

@end
