#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol CustomEzsignfolderezsigntemplatepublicSignerResponse
@end

@interface CustomEzsignfolderezsigntemplatepublicSignerResponse : Object

/* The unique ID of the User [optional]
 */
@property(nonatomic) NSNumber* fkiUserID;
/* The unique ID of the Ezsignsignergroup [optional]
 */
@property(nonatomic) NSNumber* fkiEzsignsignergroupID;
/* The First name of the contact [optional]
 */
@property(nonatomic) NSString* sContactFirstname;
/* The Last name of the contact [optional]
 */
@property(nonatomic) NSString* sContactLastname;
/* The Description of the Ezsignsignergroup in the language of the requester [optional]
 */
@property(nonatomic) NSString* sEzsignsignergroupDescriptionX;

@end
