#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "MultilingualEzmaxcustomerCompany.h"
@protocol MultilingualEzmaxcustomerCompany;
@class MultilingualEzmaxcustomerCompany;



@protocol CustomEzmaxcustomerResponse
@end

@interface CustomEzmaxcustomerResponse : Object

/* The Ezmaxcustomer code 
 */
@property(nonatomic) NSString* fksEzmaxcustomerCode;
/* The unique ID of the Systemconfigurationtype 
 */
@property(nonatomic) NSNumber* fkiSystemconfigurationtypeID;

@property(nonatomic) MultilingualEzmaxcustomerCompany* objEzmaxcustomerCompany;

@end
