#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AttachmentResponse.h"
#import "AttachmentResponseCompound.h"
#import "CommonAudit.h"
#import "FieldEAttachmentDocumenttype.h"
#import "FieldEAttachmentPrivacy.h"
#import "FieldEAttachmentType.h"
#import "FieldEAttachmentVerified.h"
@protocol AttachmentResponse;
@class AttachmentResponse;
@protocol AttachmentResponseCompound;
@class AttachmentResponseCompound;
@protocol CommonAudit;
@class CommonAudit;
@protocol FieldEAttachmentDocumenttype;
@class FieldEAttachmentDocumenttype;
@protocol FieldEAttachmentPrivacy;
@class FieldEAttachmentPrivacy;
@protocol FieldEAttachmentType;
@class FieldEAttachmentType;
@protocol FieldEAttachmentVerified;
@class FieldEAttachmentVerified;



@protocol CustomAttachmentResponse
@end

@interface CustomAttachmentResponse : AttachmentResponse


@property(nonatomic) AttachmentResponseCompound* objAttachmentProof;

@property(nonatomic) AttachmentResponseCompound* objAttachmentProofdocument;

@property(nonatomic) NSArray<AttachmentResponseCompound>* aObjAttachmentAttachment;

@property(nonatomic) NSArray<AttachmentResponseCompound>* aObjAttachmentVersion;

@end
