#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomCreateEzsignelementsPositionedByWordRequest.h"
#import "EnumTextvalidation.h"
#import "EzsignelementdependencyRequest.h"
#import "EzsignsignatureRequestCompound.h"
#import "EzsignsignaturecustomdateRequest.h"
#import "FieldEEzsignsignatureAttachmentnamesource.h"
#import "FieldEEzsignsignatureConsultationtrigger.h"
#import "FieldEEzsignsignatureDependencyrequirement.h"
#import "FieldEEzsignsignatureFont.h"
#import "FieldEEzsignsignatureTooltipposition.h"
#import "FieldEEzsignsignatureType.h"
@protocol CustomCreateEzsignelementsPositionedByWordRequest;
@class CustomCreateEzsignelementsPositionedByWordRequest;
@protocol EnumTextvalidation;
@class EnumTextvalidation;
@protocol EzsignelementdependencyRequest;
@class EzsignelementdependencyRequest;
@protocol EzsignsignatureRequestCompound;
@class EzsignsignatureRequestCompound;
@protocol EzsignsignaturecustomdateRequest;
@class EzsignsignaturecustomdateRequest;
@protocol FieldEEzsignsignatureAttachmentnamesource;
@class FieldEEzsignsignatureAttachmentnamesource;
@protocol FieldEEzsignsignatureConsultationtrigger;
@class FieldEEzsignsignatureConsultationtrigger;
@protocol FieldEEzsignsignatureDependencyrequirement;
@class FieldEEzsignsignatureDependencyrequirement;
@protocol FieldEEzsignsignatureFont;
@class FieldEEzsignsignatureFont;
@protocol FieldEEzsignsignatureTooltipposition;
@class FieldEEzsignsignatureTooltipposition;
@protocol FieldEEzsignsignatureType;
@class FieldEEzsignsignatureType;



@protocol CustomEzsignsignatureCreateEzsignelementsPositionedByWordRequest
@end

@interface CustomEzsignsignatureCreateEzsignelementsPositionedByWordRequest : EzsignsignatureRequestCompound


@property(nonatomic) CustomCreateEzsignelementsPositionedByWordRequest* objCreateezsignelementspositionedbyword;

@end
