#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol CustomCommunicationsenderRequest
@end

@interface CustomCommunicationsenderRequest : Object

/* The unique ID of the Agent. [optional]
 */
@property(nonatomic) NSNumber* fkiAgentID;
/* The unique ID of the Broker. [optional]
 */
@property(nonatomic) NSNumber* fkiBrokerID;
/* The unique ID of the Mailboxshared [optional]
 */
@property(nonatomic) NSNumber* fkiMailboxsharedID;
/* The unique ID of the Phonelineshared [optional]
 */
@property(nonatomic) NSNumber* fkiPhonelinesharedID;
/* The unique ID of the User [optional]
 */
@property(nonatomic) NSNumber* fkiUserID;

@end
