#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomFormDataEzsignformfieldgroupResponse.h"
@protocol CustomFormDataEzsignformfieldgroupResponse;
@class CustomFormDataEzsignformfieldgroupResponse;



@protocol CustomFormDataSignerResponse
@end

@interface CustomFormDataSignerResponse : Object

/* The unique ID of the Ezsignfoldersignerassociation 
 */
@property(nonatomic) NSNumber* fkiEzsignfoldersignerassociationID;
/* The unique ID of the User [optional]
 */
@property(nonatomic) NSNumber* fkiUserID;
/* The First name of the contact 
 */
@property(nonatomic) NSString* sContactFirstname;
/* The Last name of the contact 
 */
@property(nonatomic) NSString* sContactLastname;

@property(nonatomic) NSArray<CustomFormDataEzsignformfieldgroupResponse>* aObjEzsignformfieldgroup;

@end
