#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldECreditcardtransactionAvsresult.h"
#import "FieldECreditcardtransactionCvdresult.h"
@protocol FieldECreditcardtransactionAvsresult;
@class FieldECreditcardtransactionAvsresult;
@protocol FieldECreditcardtransactionCvdresult;
@class FieldECreditcardtransactionCvdresult;



@protocol CustomCreditcardtransactionresponseResponse
@end

@interface CustomCreditcardtransactionresponseResponse : Object

/* The ISO code 
 */
@property(nonatomic) NSString* sCreditcardtransactionISOcode;
/* The response code 
 */
@property(nonatomic) NSString* sCreditcardtransactionResponsecode;
/* The terminal response message 
 */
@property(nonatomic) NSString* sCreditcardtransactionResponseterminalmessage;

@property(nonatomic) FieldECreditcardtransactionAvsresult* eCreditcardtransactionAvsresult;

@property(nonatomic) FieldECreditcardtransactionCvdresult* eCreditcardtransactionCvdresult;

@end
