#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomEzsignsignaturestatusResponse.h"
@protocol CustomEzsignsignaturestatusResponse;
@class CustomEzsignsignaturestatusResponse;



@protocol CustomEzsignfoldersignerassociationstatusResponse
@end

@interface CustomEzsignfoldersignerassociationstatusResponse : Object

/* The unique ID of the Ezsignfoldersignerassociation 
 */
@property(nonatomic) NSNumber* fkiEzsignfoldersignerassociationID;
/* The last name of the Ezsignsigner [optional]
 */
@property(nonatomic) NSString* sEzsignfoldersignerassociationstatusLastname;
/* The first name of the Ezsignsigner [optional]
 */
@property(nonatomic) NSString* sEzsignfoldersignerassociationstatusFirstname;
/* The description of the Ezsignsigner [optional]
 */
@property(nonatomic) NSString* sEzsignfoldersignerassociationstatusDescriptionX;

@property(nonatomic) NSArray<CustomEzsignsignaturestatusResponse>* aObjEzsignsignaturestatus;

@end
