#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol CustomEzsignimportdocumentResponse
@end

@interface CustomEzsignimportdocumentResponse : Object

/* The unique ID of the Ezsignimportdocument 
 */
@property(nonatomic) NSNumber* pkiEzsignimportdocumentID;
/* The name of the Ezsignimportdocument 
 */
@property(nonatomic) NSString* sEzsignimportdocumentName;
/* The unique ID of the Ezsigntemplateglobal [optional]
 */
@property(nonatomic) NSNumber* fkiEzsigntemplateglobalID;
/* The description of the Ezsigntemplate [optional]
 */
@property(nonatomic) NSString* sEzsigntemplateglobalDescription;
/* The unique ID of the Ezsignfolder [optional]
 */
@property(nonatomic) NSNumber* fkiEzsignfolderID;
/* The description of the Ezsignfolder [optional]
 */
@property(nonatomic) NSString* sEzsignfolderDescription;

@end
