#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZAuthenticateAuthenticateV2ResponseAllOf.h"
#import "EZAuthenticateAuthenticateV2ResponseMPayload.h"
#import "EZCommonResponse.h"
#import "EZCommonResponseObjDebug.h"
#import "EZCommonResponseObjDebugPayload.h"
@protocol EZAuthenticateAuthenticateV2ResponseAllOf;
@class EZAuthenticateAuthenticateV2ResponseAllOf;
@protocol EZAuthenticateAuthenticateV2ResponseMPayload;
@class EZAuthenticateAuthenticateV2ResponseMPayload;
@protocol EZCommonResponse;
@class EZCommonResponse;
@protocol EZCommonResponseObjDebug;
@class EZCommonResponseObjDebug;
@protocol EZCommonResponseObjDebugPayload;
@class EZCommonResponseObjDebugPayload;



@protocol EZAuthenticateAuthenticateV2Response
@end

@interface EZAuthenticateAuthenticateV2Response : EZObject


@property(nonatomic) EZAuthenticateAuthenticateV2ResponseMPayload* mPayload;

@property(nonatomic) EZCommonResponseObjDebugPayload* objDebugPayload;

@property(nonatomic) EZCommonResponseObjDebug* objDebug;

@end
