#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZBillingentityinternalCreateObjectV1ResponseMPayload.h"
@protocol EZBillingentityinternalCreateObjectV1ResponseMPayload;
@class EZBillingentityinternalCreateObjectV1ResponseMPayload;



@protocol EZBillingentityinternalCreateObjectV1ResponseAllOf
@end

@interface EZBillingentityinternalCreateObjectV1ResponseAllOf : EZObject


@property(nonatomic) EZBillingentityinternalCreateObjectV1ResponseMPayload* mPayload;

@end
