#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCorsRequestCompound.h"
@protocol EZCorsRequestCompound;
@class EZCorsRequestCompound;



@protocol EZCorsEditObjectV1Request
@end

@interface EZCorsEditObjectV1Request : EZObject


@property(nonatomic) EZCorsRequestCompound* objCors;

@end
