#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCustomContactNameResponse.h"
#import "EZFieldECommunicationEmailimportance.h"
#import "EZFieldECommunicationType.h"
@protocol EZCustomContactNameResponse;
@class EZCustomContactNameResponse;
@protocol EZFieldECommunicationEmailimportance;
@class EZFieldECommunicationEmailimportance;
@protocol EZFieldECommunicationType;
@class EZFieldECommunicationType;



@protocol EZCommunicationResponse
@end

@interface EZCommunicationResponse : EZObject

/* The unique ID of the Communication. 
 */
@property(nonatomic) NSNumber* pkiCommunicationID;

@property(nonatomic) EZFieldECommunicationEmailimportance* eCommunicationEmailimportance;

@property(nonatomic) EZFieldECommunicationType* eCommunicationType;
/* The Subject of the Communication 
 */
@property(nonatomic) NSString* sCommunicationSubject;
/* The send date and time at which the Communication was sent. 
 */
@property(nonatomic) NSString* dtCommunicationSentdate;

@property(nonatomic) EZCustomContactNameResponse* objContactFrom;

@end
