#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZFieldECommunicationexternalrecipientType.h"
#import "EZPhoneResponseCompound.h"
@protocol EZFieldECommunicationexternalrecipientType;
@class EZFieldECommunicationexternalrecipientType;
@protocol EZPhoneResponseCompound;
@class EZPhoneResponseCompound;



@protocol EZCommunicationexternalrecipientResponseCompound
@end

@interface EZCommunicationexternalrecipientResponseCompound : EZObject

/* The unique ID of the Communicationexternalrecipient 
 */
@property(nonatomic) NSNumber* pkiCommunicationexternalrecipientID;
/* The email address. [optional]
 */
@property(nonatomic) NSString* sEmailAddress;

@property(nonatomic) EZPhoneResponseCompound* objPhoneSms;

@property(nonatomic) EZFieldECommunicationexternalrecipientType* eCommunicationexternalrecipientType;
/* The Name of the Communicationexternalrecipient 
 */
@property(nonatomic) NSString* sCommunicationexternalrecipientName;

@end
