#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCustomEzsignformfielderrorResponse.h"
#import "EZFieldEErrorCode.h"
@protocol EZCustomEzsignformfielderrorResponse;
@class EZCustomEzsignformfielderrorResponse;
@protocol EZFieldEErrorCode;
@class EZFieldEErrorCode;



@protocol EZCommonResponseErrorEzsignformValidation
@end

@interface EZCommonResponseErrorEzsignformValidation : EZObject

/*  
 */
@property(nonatomic) NSArray<EZCustomEzsignformfielderrorResponse>* aObjEzsignformfielderror;
/* The message giving details about the error 
 */
@property(nonatomic) NSString* sErrorMessage;

@property(nonatomic) EZFieldEErrorCode* eErrorCode;

@end
