#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCommunicationattachmentResponseCompound.h"
#import "EZCommunicationexternalrecipientResponseCompound.h"
#import "EZCommunicationrecipientResponseCompound.h"
@protocol EZCommunicationattachmentResponseCompound;
@class EZCommunicationattachmentResponseCompound;
@protocol EZCommunicationexternalrecipientResponseCompound;
@class EZCommunicationexternalrecipientResponseCompound;
@protocol EZCommunicationrecipientResponseCompound;
@class EZCommunicationrecipientResponseCompound;



@protocol EZCommunicationResponseCompoundAllOf
@end

@interface EZCommunicationResponseCompoundAllOf : EZObject


@property(nonatomic) NSArray<EZCommunicationattachmentResponseCompound>* aObjCommunicationattachment;

@property(nonatomic) NSArray<EZCommunicationrecipientResponseCompound>* aObjCommunicationrecipient;

@property(nonatomic) NSArray<EZCommunicationexternalrecipientResponseCompound>* aObjCommunicationexternalrecipient;

@end
