#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EZCommonResponseWarning
@end

@interface EZCommonResponseWarning : EZObject

/* More detail about the warning 
 */
@property(nonatomic) NSString* sWarningMessage;
/* The warning code. See documentation for valid values 
 */
@property(nonatomic) NSString* eWarningCode;

@end
