#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EZCommunicationattachmentResponse
@end

@interface EZCommunicationattachmentResponse : EZObject

/* The unique ID of the Communicationattachment 
 */
@property(nonatomic) NSNumber* pkiCommunicationattachmentID;
/* The unique ID of the Attachment. [optional]
 */
@property(nonatomic) NSNumber* fkiAttachmentID;
/* The unique ID of the Invoice. [optional]
 */
@property(nonatomic) NSNumber* fkiInvoiceID;
/* The unique ID of the Salarypreparation. [optional]
 */
@property(nonatomic) NSNumber* fkiSalarypreparationID;
/* The name of the Communicationattachment 
 */
@property(nonatomic) NSString* sCommunicationattachmentName;
/* The Url to the requested document.  Url will expire after 3 hours. [optional]
 */
@property(nonatomic) NSString* sDownloadUrl;

@end
