#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCustomEzsigndocumentEzsignsignaturesAutomaticResponse.h"
@protocol EZCustomEzsigndocumentEzsignsignaturesAutomaticResponse;
@class EZCustomEzsigndocumentEzsignsignaturesAutomaticResponse;



@protocol EZCustomEzsignfolderEzsignsignaturesAutomaticResponse
@end

@interface EZCustomEzsignfolderEzsignsignaturesAutomaticResponse : EZObject

/* The unique ID of the Ezsignfolder 
 */
@property(nonatomic) NSNumber* pkiEzsignfolderID;
/* The description of the Ezsignfolder 
 */
@property(nonatomic) NSString* sEzsignfolderDescription;

@property(nonatomic) NSArray<EZCustomEzsigndocumentEzsignsignaturesAutomaticResponse>* aObjEzsigndocument;

@end
