#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZComputedECommunicationDirection.h"
#import "EZFieldECommunicationImportance.h"
#import "EZFieldECommunicationType.h"
@protocol EZComputedECommunicationDirection;
@class EZComputedECommunicationDirection;
@protocol EZFieldECommunicationImportance;
@class EZFieldECommunicationImportance;
@protocol EZFieldECommunicationType;
@class EZFieldECommunicationType;



@protocol EZCustomCommunicationListElementResponse
@end

@interface EZCustomCommunicationListElementResponse : EZObject

/* The unique ID of the Communication. 
 */
@property(nonatomic) NSNumber* pkiCommunicationID;
/* The date and time at which the object was created 
 */
@property(nonatomic) NSString* dtCreatedDate;

@property(nonatomic) EZComputedECommunicationDirection* eCommunicationDirection;

@property(nonatomic) EZFieldECommunicationImportance* eCommunicationImportance;

@property(nonatomic) EZFieldECommunicationType* eCommunicationType;
/* The count of Communicationrecipient 
 */
@property(nonatomic) NSNumber* iCommunicationrecipientCount;
/* The subject of the Communication 
 */
@property(nonatomic) NSString* sCommunicationSubject;
/* The sender name of the Communication 
 */
@property(nonatomic) NSString* sCommunicationSender;
/* The recipients' name of the Communication 
 */
@property(nonatomic) NSString* sCommunicationRecipient;

@end
