#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.16
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EZCustomContactNameResponse
@end

@interface EZCustomContactNameResponse : EZObject

/* The First name of the contact [optional]
 */
@property(nonatomic) NSString* sContactFirstname;
/* The Last name of the contact [optional]
 */
@property(nonatomic) NSString* sContactLastname;
/* The Company name of the contact [optional]
 */
@property(nonatomic) NSString* sContactCompany;

@end
