#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsignbulksenddocumentmappingCreateObjectV1ResponseMPayload.h"
@protocol EZEzsignbulksenddocumentmappingCreateObjectV1ResponseMPayload;
@class EZEzsignbulksenddocumentmappingCreateObjectV1ResponseMPayload;



@protocol EZEzsignbulksenddocumentmappingCreateObjectV1ResponseAllOf
@end

@interface EZEzsignbulksenddocumentmappingCreateObjectV1ResponseAllOf : EZObject


@property(nonatomic) EZEzsignbulksenddocumentmappingCreateObjectV1ResponseMPayload* mPayload;

@end
