#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsigndocumentlogResponse.h"
@protocol EZEzsigndocumentlogResponse;
@class EZEzsigndocumentlogResponse;



@protocol EZEzsigndocumentGetTemporaryProofV1ResponseMPayload
@end

@interface EZEzsigndocumentGetTemporaryProofV1ResponseMPayload : EZObject


@property(nonatomic) EZEzsigndocumentlogResponse* aObjEzsigndocumentlog;

@end
