#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.13
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsigntemplateformfieldgroupResponseCompound.h"
@protocol EZEzsigntemplateformfieldgroupResponseCompound;
@class EZEzsigntemplateformfieldgroupResponseCompound;



@protocol EZEzsigntemplateformfieldgroupGetObjectV2ResponseMPayload
@end

@interface EZEzsigntemplateformfieldgroupGetObjectV2ResponseMPayload : EZObject


@property(nonatomic) EZEzsigntemplateformfieldgroupResponseCompound* objEzsigntemplateformfieldgroup;

@end
