#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsignfolderGetEzsignfoldersignerassociationsmineV1ResponseMPayload.h"
@protocol EZEzsignfolderGetEzsignfoldersignerassociationsmineV1ResponseMPayload;
@class EZEzsignfolderGetEzsignfoldersignerassociationsmineV1ResponseMPayload;



@protocol EZEzsignfolderGetEzsignfoldersignerassociationsmineV1ResponseAllOf
@end

@interface EZEzsignfolderGetEzsignfoldersignerassociationsmineV1ResponseAllOf : EZObject


@property(nonatomic) EZEzsignfolderGetEzsignfoldersignerassociationsmineV1ResponseMPayload* mPayload;

@end
