#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.16
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsigntemplatepackagemembershipRequest.h"
@protocol EZEzsigntemplatepackagemembershipRequest;
@class EZEzsigntemplatepackagemembershipRequest;



@protocol EZEzsigntemplatepackagemembershipRequestCompound
@end

@interface EZEzsigntemplatepackagemembershipRequestCompound : EZObject

/* The unique ID of the Ezsigntemplatepackagemembership [optional]
 */
@property(nonatomic) NSNumber* pkiEzsigntemplatepackagemembershipID;
/* The unique ID of the Ezsigntemplatepackage 
 */
@property(nonatomic) NSNumber* fkiEzsigntemplatepackageID;
/* The unique ID of the Ezsigntemplate 
 */
@property(nonatomic) NSNumber* fkiEzsigntemplateID;

@end
