#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.7
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCommonResponse.h"
#import "EZCommonResponseObjDebug.h"
#import "EZCommonResponseObjDebugPayload.h"
#import "EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf.h"
#import "EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload.h"
@protocol EZCommonResponse;
@class EZCommonResponse;
@protocol EZCommonResponseObjDebug;
@class EZCommonResponseObjDebug;
@protocol EZCommonResponseObjDebugPayload;
@class EZCommonResponseObjDebugPayload;
@protocol EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf;
@class EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf;
@protocol EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload;
@class EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload;



@protocol EZEzsignfolderGetEzsignfoldersignerassociationsV1Response
@end

@interface EZEzsignfolderGetEzsignfoldersignerassociationsV1Response : EZObject


@property(nonatomic) EZEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload* mPayload;

@property(nonatomic) EZCommonResponseObjDebugPayload* objDebugPayload;

@property(nonatomic) EZCommonResponseObjDebug* objDebug;

@end
