#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.10
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsignsignatureResponseCompound.h"
@protocol EZEzsignsignatureResponseCompound;
@class EZEzsignsignatureResponseCompound;



@protocol EZEzsigndocumentGetEzsignsignaturesV1ResponseMPayload
@end

@interface EZEzsigndocumentGetEzsignsignaturesV1ResponseMPayload : EZObject


@property(nonatomic) NSArray<EZEzsignsignatureResponseCompound>* aObjEzsignsignature;

@end
