#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload.h"
@protocol EZEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload;
@class EZEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload;



@protocol EZEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf
@end

@interface EZEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf : EZObject


@property(nonatomic) EZEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload* mPayload;

@end
