#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZFontAutocompleteElementResponse.h"
@protocol EZFontAutocompleteElementResponse;
@class EZFontAutocompleteElementResponse;



@protocol EZFontGetAutocompleteV2ResponseMPayload
@end

@interface EZFontGetAutocompleteV2ResponseMPayload : EZObject

/* An array of Font autocomplete element response. [optional]
 */
@property(nonatomic) NSArray<EZFontAutocompleteElementResponse>* aObjFont;

@end
