#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZCommonResponse.h"
#import "EZCommonResponseObjDebug.h"
#import "EZCommonResponseObjDebugPayload.h"
#import "EZListGetListpresentationV1ResponseAllOf.h"
#import "EZListGetListpresentationV1ResponseMPayload.h"
@protocol EZCommonResponse;
@class EZCommonResponse;
@protocol EZCommonResponseObjDebug;
@class EZCommonResponseObjDebug;
@protocol EZCommonResponseObjDebugPayload;
@class EZCommonResponseObjDebugPayload;
@protocol EZListGetListpresentationV1ResponseAllOf;
@class EZListGetListpresentationV1ResponseAllOf;
@protocol EZListGetListpresentationV1ResponseMPayload;
@class EZListGetListpresentationV1ResponseMPayload;



@protocol EZListGetListpresentationV1Response
@end

@interface EZListGetListpresentationV1Response : EZObject


@property(nonatomic) EZListGetListpresentationV1ResponseMPayload* mPayload;

@property(nonatomic) EZCommonResponseObjDebugPayload* objDebugPayload;

@property(nonatomic) EZCommonResponseObjDebug* objDebug;

@end
