#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EzmaxcaseRequestPatch
@end

@interface EzmaxcaseRequestPatch : Object

/* The unique ID of the Ezmaxcasequeue [optional]
 */
@property(nonatomic) NSNumber* fkiEzmaxcasequeueID;
/* The unique ID of the Ezmaxcasepriority [optional]
 */
@property(nonatomic) NSNumber* fkiEzmaxcasepriorityID;
/* The unique ID of the Ezmaxcasestate [optional]
 */
@property(nonatomic) NSNumber* fkiEzmaxcasestateID;
/* The unique ID of the Ezmaxfeaturerequest [optional]
 */
@property(nonatomic) NSNumber* fkiEzmaxfeaturerequestID;
/* The unique ID of the Ezmaxknownissue [optional]
 */
@property(nonatomic) NSNumber* fkiEzmaxknownissueID;
/* The unique ID of the User [optional]
 */
@property(nonatomic) NSNumber* fkiUserIDOwner;

@end
