#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CommonAudit.h"
#import "CustomEzmaxpricingResponse.h"
#import "EzmaxinvoicingResponseCompound.h"
#import "EzmaxinvoicingagentResponseCompound.h"
#import "EzmaxinvoicingcontractResponseCompound.h"
#import "EzmaxinvoicingsummaryexternalResponseCompound.h"
#import "EzmaxinvoicingsummaryglobalResponseCompound.h"
#import "EzmaxinvoicingsummaryinternalResponseCompound.h"
#import "EzmaxinvoicinguserResponseCompound.h"
#import "FieldEEzmaxinvoicingPaymenttype.h"
@protocol CommonAudit;
@class CommonAudit;
@protocol CustomEzmaxpricingResponse;
@class CustomEzmaxpricingResponse;
@protocol EzmaxinvoicingResponseCompound;
@class EzmaxinvoicingResponseCompound;
@protocol EzmaxinvoicingagentResponseCompound;
@class EzmaxinvoicingagentResponseCompound;
@protocol EzmaxinvoicingcontractResponseCompound;
@class EzmaxinvoicingcontractResponseCompound;
@protocol EzmaxinvoicingsummaryexternalResponseCompound;
@class EzmaxinvoicingsummaryexternalResponseCompound;
@protocol EzmaxinvoicingsummaryglobalResponseCompound;
@class EzmaxinvoicingsummaryglobalResponseCompound;
@protocol EzmaxinvoicingsummaryinternalResponseCompound;
@class EzmaxinvoicingsummaryinternalResponseCompound;
@protocol EzmaxinvoicinguserResponseCompound;
@class EzmaxinvoicinguserResponseCompound;
@protocol FieldEEzmaxinvoicingPaymenttype;
@class FieldEEzmaxinvoicingPaymenttype;



@protocol EzmaxinvoicingGetProvisionalV1ResponseMPayload
@end

@interface EzmaxinvoicingGetProvisionalV1ResponseMPayload : EzmaxinvoicingResponseCompound


@end
