#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.3
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EzmaxmaillinglistListElement
@end

@interface EzmaxmaillinglistListElement : Object

/* The unique ID of the Ezmaxmaillinglist 
 */
@property(nonatomic) NSNumber* pkiEzmaxmaillinglistID;
/* The name of the Ezmaxmaillinglist in the language of the requester 
 */
@property(nonatomic) NSString* sEzmaxmaillinglistNameX;
/* The description of the Ezmaxmaillinglist in the language of the requester 
 */
@property(nonatomic) NSString* sEzmaxmaillinglistDescriptionX;
/* Whether the user subscribed to this Ezmaxmaillinglistor not 
 */
@property(nonatomic) NSNumber* bEzmaxmaillinglistSubscribed;

@end
