#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomContactNameResponse.h"
#import "EzmaxinvoicinguserResponse.h"
#import "FieldEEzmaxinvoicinguserVariationezsign.h"
@protocol CustomContactNameResponse;
@class CustomContactNameResponse;
@protocol EzmaxinvoicinguserResponse;
@class EzmaxinvoicinguserResponse;
@protocol FieldEEzmaxinvoicinguserVariationezsign;
@class FieldEEzmaxinvoicinguserVariationezsign;



@protocol EzmaxinvoicinguserResponseCompound
@end

@interface EzmaxinvoicinguserResponseCompound : EzmaxinvoicinguserResponse


@property(nonatomic) CustomContactNameResponse* objContactName;

@end
