#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzmaxcustomerRequestPatch.h"
@protocol EzmaxcustomerRequestPatch;
@class EzmaxcustomerRequestPatch;



@protocol EzmaxcustomerPatchObjectV1Request
@end

@interface EzmaxcustomerPatchObjectV1Request : Object


@property(nonatomic) EzmaxcustomerRequestPatch* objEzmaxcustomer;

@end
