#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZScimAuthenticationScheme.h"
#import "EZScimServiceProviderConfigBulk.h"
#import "EZScimServiceProviderConfigChangePassword.h"
#import "EZScimServiceProviderConfigEtag.h"
#import "EZScimServiceProviderConfigFilter.h"
#import "EZScimServiceProviderConfigPatch.h"
#import "EZScimServiceProviderConfigSort.h"
@protocol EZScimAuthenticationScheme;
@class EZScimAuthenticationScheme;
@protocol EZScimServiceProviderConfigBulk;
@class EZScimServiceProviderConfigBulk;
@protocol EZScimServiceProviderConfigChangePassword;
@class EZScimServiceProviderConfigChangePassword;
@protocol EZScimServiceProviderConfigEtag;
@class EZScimServiceProviderConfigEtag;
@protocol EZScimServiceProviderConfigFilter;
@class EZScimServiceProviderConfigFilter;
@protocol EZScimServiceProviderConfigPatch;
@class EZScimServiceProviderConfigPatch;
@protocol EZScimServiceProviderConfigSort;
@class EZScimServiceProviderConfigSort;



@protocol EZScimServiceProviderConfig
@end

@interface EZScimServiceProviderConfig : EZObject

/* A multi-valued complex type that specifies supported authentication scheme properties. 
 */
@property(nonatomic) NSArray<EZScimAuthenticationScheme>* authenticationSchemes;

@property(nonatomic) EZScimServiceProviderConfigBulk* bulk;

@property(nonatomic) EZScimServiceProviderConfigChangePassword* changePassword;
/* An HTTP-addressable URL pointing to the service provider's human-consumable help documentation 
 */
@property(nonatomic) NSString* documentationUri;

@property(nonatomic) EZScimServiceProviderConfigEtag* etag;

@property(nonatomic) EZScimServiceProviderConfigFilter* filter;

@property(nonatomic) EZScimServiceProviderConfigPatch* patch;

@property(nonatomic) EZScimServiceProviderConfigSort* sort;

@end
