#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CommonResponseObjDebug.h"
#import "CommonResponseObjDebugPayload.h"
#import "EzsignsignatureGetEzsignsignatureattachmentV1ResponseMPayload.h"
@protocol CommonResponseObjDebug;
@class CommonResponseObjDebug;
@protocol CommonResponseObjDebugPayload;
@class CommonResponseObjDebugPayload;
@protocol EzsignsignatureGetEzsignsignatureattachmentV1ResponseMPayload;
@class EzsignsignatureGetEzsignsignatureattachmentV1ResponseMPayload;



@protocol EzsignsignatureGetEzsignsignatureattachmentV1Response
@end

@interface EzsignsignatureGetEzsignsignatureattachmentV1Response : Object


@property(nonatomic) CommonResponseObjDebugPayload* objDebugPayload;

@property(nonatomic) CommonResponseObjDebug* objDebug;

@property(nonatomic) EzsignsignatureGetEzsignsignatureattachmentV1ResponseMPayload* mPayload;

@end
