#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EnumTextvalidation.h"
#import "EzsigntemplateelementdependencyRequest.h"
#import "EzsigntemplatesignatureRequest.h"
#import "EzsigntemplatesignaturecustomdateRequestV2.h"
#import "FieldEEzsigntemplatesignatureAttachmentnamesource.h"
#import "FieldEEzsigntemplatesignatureConsultationtrigger.h"
#import "FieldEEzsigntemplatesignatureDependencyrequirement.h"
#import "FieldEEzsigntemplatesignatureFont.h"
#import "FieldEEzsigntemplatesignaturePositioning.h"
#import "FieldEEzsigntemplatesignaturePositioningoccurence.h"
#import "FieldEEzsigntemplatesignatureTooltipposition.h"
#import "FieldEEzsigntemplatesignatureType.h"
@protocol EnumTextvalidation;
@class EnumTextvalidation;
@protocol EzsigntemplateelementdependencyRequest;
@class EzsigntemplateelementdependencyRequest;
@protocol EzsigntemplatesignatureRequest;
@class EzsigntemplatesignatureRequest;
@protocol EzsigntemplatesignaturecustomdateRequestV2;
@class EzsigntemplatesignaturecustomdateRequestV2;
@protocol FieldEEzsigntemplatesignatureAttachmentnamesource;
@class FieldEEzsigntemplatesignatureAttachmentnamesource;
@protocol FieldEEzsigntemplatesignatureConsultationtrigger;
@class FieldEEzsigntemplatesignatureConsultationtrigger;
@protocol FieldEEzsigntemplatesignatureDependencyrequirement;
@class FieldEEzsigntemplatesignatureDependencyrequirement;
@protocol FieldEEzsigntemplatesignatureFont;
@class FieldEEzsigntemplatesignatureFont;
@protocol FieldEEzsigntemplatesignaturePositioning;
@class FieldEEzsigntemplatesignaturePositioning;
@protocol FieldEEzsigntemplatesignaturePositioningoccurence;
@class FieldEEzsigntemplatesignaturePositioningoccurence;
@protocol FieldEEzsigntemplatesignatureTooltipposition;
@class FieldEEzsigntemplatesignatureTooltipposition;
@protocol FieldEEzsigntemplatesignatureType;
@class FieldEEzsigntemplatesignatureType;



@protocol EzsigntemplatesignatureRequestCompoundV2
@end

@interface EzsigntemplatesignatureRequestCompoundV2 : EzsigntemplatesignatureRequest

/* Whether the Ezsigntemplatesignature has a custom date format or not. (Only possible when eEzsigntemplatesignatureType is **Name** or **Handwritten**) [optional]
 */
@property(nonatomic) NSNumber* bEzsigntemplatesignatureCustomdate;
/* An array of custom date blocks that will be filled at the time of signature.  Can only be used if bEzsigntemplatesignatureCustomdate is true.  Use an empty array if you don't want to have a date at all. [optional]
 */
@property(nonatomic) NSArray<EzsigntemplatesignaturecustomdateRequestCompoundV2>* aObjEzsigntemplatesignaturecustomdate;

@property(nonatomic) NSArray<EzsigntemplateelementdependencyRequestCompound>* aObjEzsigntemplateelementdependency;

@end
