#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsigndocumentMatchingtemplateV3Response.h"
@protocol EzsigndocumentMatchingtemplateV3Response;
@class EzsigndocumentMatchingtemplateV3Response;



@protocol EzsigndocumentCreateElementV3Response
@end

@interface EzsigndocumentCreateElementV3Response : Object

/* The unique ID of the Ezsigndocument 
 */
@property(nonatomic) NSNumber* pkiEzsigndocumentID;
/* An array of possibly matching template. 
 */
@property(nonatomic) NSArray<EzsigndocumentMatchingtemplateV3Response>* aObjMatchingtemplate;

@end
