#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldEEzsigntemplateType.h"
@protocol FieldEEzsigntemplateType;
@class FieldEEzsigntemplateType;



@protocol EzsigntemplateListElement
@end

@interface EzsigntemplateListElement : Object

/* The unique ID of the Ezsigntemplate 
 */
@property(nonatomic) NSNumber* pkiEzsigntemplateID;
/* The unique ID of the Ezsignfoldertype. [optional]
 */
@property(nonatomic) NSNumber* fkiEzsignfoldertypeID;
/* The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English| 
 */
@property(nonatomic) NSNumber* fkiLanguageID;
/* The description of the Ezsigntemplate 
 */
@property(nonatomic) NSString* sEzsigntemplateDescription;
/* The number of pages in the Ezsigntemplatedocument. [optional]
 */
@property(nonatomic) NSNumber* iEzsigntemplatedocumentPagetotal;
/* The number of total signatures in the Ezsigntemplate. [optional]
 */
@property(nonatomic) NSNumber* iEzsigntemplateSignaturetotal;
/* The number of total form fields in the Ezsigntemplate. [optional]
 */
@property(nonatomic) NSNumber* iEzsigntemplateFormfieldtotal;
/* Indicate the Ezsigntemplate is incomplete and cannot be used 
 */
@property(nonatomic) NSNumber* bEzsigntemplateIncomplete;
/* The name of the Ezsignfoldertype in the language of the requester [optional]
 */
@property(nonatomic) NSString* sEzsignfoldertypeNameX;

@property(nonatomic) FieldEEzsigntemplateType* eEzsigntemplateType;

@end
