#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsignsignerResponse.h"
#import "EzsignsignerResponseCompoundContact.h"
@protocol EzsignsignerResponse;
@class EzsignsignerResponse;
@protocol EzsignsignerResponseCompoundContact;
@class EzsignsignerResponseCompoundContact;



@protocol EzsignsignerResponseCompound
@end

@interface EzsignsignerResponseCompound : EzsignsignerResponse


@property(nonatomic) EzsignsignerResponseCompoundContact* objContact;

@end
