#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsigntemplatedocumentpagerecognitionResponse.h"
#import "FieldEEzsigntemplatedocumentpagerecognitionOperator.h"
#import "FieldEEzsigntemplatedocumentpagerecognitionSection.h"
@protocol EzsigntemplatedocumentpagerecognitionResponse;
@class EzsigntemplatedocumentpagerecognitionResponse;
@protocol FieldEEzsigntemplatedocumentpagerecognitionOperator;
@class FieldEEzsigntemplatedocumentpagerecognitionOperator;
@protocol FieldEEzsigntemplatedocumentpagerecognitionSection;
@class FieldEEzsigntemplatedocumentpagerecognitionSection;



@protocol EzsigntemplatedocumentpagerecognitionResponseCompound
@end

@interface EzsigntemplatedocumentpagerecognitionResponseCompound : EzsigntemplatedocumentpagerecognitionResponse


@end
