#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EzsignsigningreasonListElement
@end

@interface EzsignsigningreasonListElement : Object

/* The unique ID of the Ezsignsigningreason 
 */
@property(nonatomic) NSNumber* pkiEzsignsigningreasonID;
/* The description of the Ezsignsigningreason in the language of the requester 
 */
@property(nonatomic) NSString* sEzsignsigningreasonDescriptionX;
/* Whether the ezsignsigningreason is active or not 
 */
@property(nonatomic) NSNumber* bEzsignsigningreasonIsactive;

@end
