#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsigntemplatesignerResponseCompound.h"
@protocol EzsigntemplatesignerResponseCompound;
@class EzsigntemplatesignerResponseCompound;



@protocol EzsigntemplatesignerGetObjectV2ResponseMPayload
@end

@interface EzsigntemplatesignerGetObjectV2ResponseMPayload : Object


@property(nonatomic) EzsigntemplatesignerResponseCompound* objEzsigntemplatesigner;

@end
