#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsignfoldersignerassociationResponseCompoundUser.h"
#import "EzsignsignerResponseCompound.h"
#import "EzsignsignergroupResponseCompound.h"
#import "FieldEEzsignfoldersignerassociationRole.h"
@protocol EzsignfoldersignerassociationResponseCompoundUser;
@class EzsignfoldersignerassociationResponseCompoundUser;
@protocol EzsignsignerResponseCompound;
@class EzsignsignerResponseCompound;
@protocol EzsignsignergroupResponseCompound;
@class EzsignsignergroupResponseCompound;
@protocol FieldEEzsignfoldersignerassociationRole;
@class FieldEEzsignfoldersignerassociationRole;



@protocol EzsignfoldersignerassociationResponseCompoundV3
@end

@interface EzsignfoldersignerassociationResponseCompoundV3 : Object

/* The unique ID of the Ezsignfoldersignerassociation 
 */
@property(nonatomic) NSNumber* pkiEzsignfoldersignerassociationID;
/* The unique ID of the Ezsignfolder 
 */
@property(nonatomic) NSNumber* fkiEzsignfolderID;
/* If this flag is true the signatory is part of a delayed send. 
 */
@property(nonatomic) NSNumber* bEzsignfoldersignerassociationDelayedsend;

@property(nonatomic) FieldEEzsignfoldersignerassociationRole* eEzsignfoldersignerassociationRole;
/* A custom text message that will be added to the email sent. 
 */
@property(nonatomic) NSString* tEzsignfoldersignerassociationMessage;
/* If the Ezsignfoldersignerassociation is allowed to sign in person or not 
 */
@property(nonatomic) NSNumber* bEzsignfoldersignerassociationAllowsigninginperson;

@property(nonatomic) EzsignsignergroupResponseCompound* objEzsignsignergroup;

@property(nonatomic) EzsignfoldersignerassociationResponseCompoundUser* objUser;

@property(nonatomic) EzsignsignerResponseCompound* objEzsignsigner;

@end
