#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsigntemplateListElement.h"
@protocol EzsigntemplateListElement;
@class EzsigntemplateListElement;



@protocol EzsigntemplateGetListV1ResponseMPayload
@end

@interface EzsigntemplateGetListV1ResponseMPayload : Object

/* The number of rows returned 
 */
@property(nonatomic) NSNumber* iRowReturned;
/* The number of rows matching your filters (if any) or the total number of rows 
 */
@property(nonatomic) NSNumber* iRowFiltered;

@property(nonatomic) NSArray<EzsigntemplateListElement>* aObjEzsigntemplate;

@end
