#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomDropdownElementRequest.h"
#import "EnumTextvalidation.h"
#import "EzsignformfieldRequestCompound.h"
#import "EzsignformfieldgroupRequest.h"
#import "EzsignformfieldgroupsignerRequest.h"
#import "FieldEEzsignformfieldgroupSignerrequirement.h"
#import "FieldEEzsignformfieldgroupTooltipposition.h"
#import "FieldEEzsignformfieldgroupType.h"
@protocol CustomDropdownElementRequest;
@class CustomDropdownElementRequest;
@protocol EnumTextvalidation;
@class EnumTextvalidation;
@protocol EzsignformfieldRequestCompound;
@class EzsignformfieldRequestCompound;
@protocol EzsignformfieldgroupRequest;
@class EzsignformfieldgroupRequest;
@protocol EzsignformfieldgroupsignerRequest;
@class EzsignformfieldgroupsignerRequest;
@protocol FieldEEzsignformfieldgroupSignerrequirement;
@class FieldEEzsignformfieldgroupSignerrequirement;
@protocol FieldEEzsignformfieldgroupTooltipposition;
@class FieldEEzsignformfieldgroupTooltipposition;
@protocol FieldEEzsignformfieldgroupType;
@class FieldEEzsignformfieldgroupType;



@protocol EzsignformfieldgroupRequestCompound
@end

@interface EzsignformfieldgroupRequestCompound : EzsignformfieldgroupRequest


@property(nonatomic) NSArray<EzsignformfieldgroupsignerRequestCompound>* aObjEzsignformfieldgroupsigner;

@property(nonatomic) NSArray<CustomDropdownElementRequestCompound>* aObjDropdownElement;

@property(nonatomic) NSArray<EzsignformfieldRequestCompound>* aObjEzsignformfield;

@end
