#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol EzsigndocumentApplyEzsigntemplateglobalV2Request
@end

@interface EzsigndocumentApplyEzsigntemplateglobalV2Request : Object

/* The unique ID of the Ezsigntemplateglobal 
 */
@property(nonatomic) NSNumber* fkiEzsigntemplateglobalID;

@property(nonatomic) NSArray<NSString*>* aSEzsigntemplateglobalsigner;

@property(nonatomic) NSArray<NSNumber*>* aFkiEzsignfoldersignerassociationID;

@property(nonatomic) NSArray<NSString*>* aSEzsigntemplateglobalannotationDescription;

@property(nonatomic) NSArray<NSString*>* aSEzsigntemplateglobalannotationDefaulttext;

@end
