#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsigntemplateResponseCompound.h"
#import "EzsigntemplatepackageResponseCompound.h"
@protocol EzsigntemplateResponseCompound;
@class EzsigntemplateResponseCompound;
@protocol EzsigntemplatepackageResponseCompound;
@class EzsigntemplatepackageResponseCompound;



@protocol EzsignSuggestTemplatesV1ResponseMPayload
@end

@interface EzsignSuggestTemplatesV1ResponseMPayload : Object


@property(nonatomic) NSArray<EzsigntemplateResponseCompound>* aObjEzsigntemplate;

@property(nonatomic) NSArray<EzsigntemplatepackageResponseCompound>* aObjEzsigntemplatepackage;

@end
