#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EzsigntemplatedocumentRequestCompound.h"
@protocol EzsigntemplatedocumentRequestCompound;
@class EzsigntemplatedocumentRequestCompound;



@protocol EzsigntemplatedocumentEditObjectV1Request
@end

@interface EzsigntemplatedocumentEditObjectV1Request : Object


@property(nonatomic) EzsigntemplatedocumentRequestCompound* objEzsigntemplatedocument;

@end
