#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZUsergroupGetPermissionsV1ResponseMPayload.h"
@protocol EZUsergroupGetPermissionsV1ResponseMPayload;
@class EZUsergroupGetPermissionsV1ResponseMPayload;



@protocol EZUsergroupGetPermissionsV1ResponseAllOf
@end

@interface EZUsergroupGetPermissionsV1ResponseAllOf : EZObject


@property(nonatomic) EZUsergroupGetPermissionsV1ResponseMPayload* mPayload;

@end
