#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.15
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZUserCreateEzsignuserV1ResponseMPayload.h"
@protocol EZUserCreateEzsignuserV1ResponseMPayload;
@class EZUserCreateEzsignuserV1ResponseMPayload;



@protocol EZUserCreateEzsignuserV1ResponseAllOf
@end

@interface EZUserCreateEzsignuserV1ResponseAllOf : EZObject


@property(nonatomic) EZUserCreateEzsignuserV1ResponseMPayload* mPayload;

@end
