#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZFieldEUserEzsignaccess.h"
#import "EZFieldEUserOrigin.h"
#import "EZFieldEUserType.h"
@protocol EZFieldEUserEzsignaccess;
@class EZFieldEUserEzsignaccess;
@protocol EZFieldEUserOrigin;
@class EZFieldEUserOrigin;
@protocol EZFieldEUserType;
@class EZFieldEUserType;



@protocol EZUserListElement
@end

@interface EZUserListElement : EZObject

/* The unique ID of the User 
 */
@property(nonatomic) NSNumber* pkiUserID;
/* The first name of the user 
 */
@property(nonatomic) NSString* sUserFirstname;
/* The last name of the user 
 */
@property(nonatomic) NSString* sUserLastname;
/* The login name of the User. 
 */
@property(nonatomic) NSString* sUserLoginname;
/* Whether the User is active or not 
 */
@property(nonatomic) NSNumber* bUserIsactive;

@property(nonatomic) EZFieldEUserType* eUserType;

@property(nonatomic) EZFieldEUserOrigin* eUserOrigin;

@property(nonatomic) EZFieldEUserEzsignaccess* eUserEzsignaccess;
/* The eZsign prepaid expiration date [optional]
 */
@property(nonatomic) NSString* dtUserEzsignprepaidexpiration;
/* The email address. 
 */
@property(nonatomic) NSString* sEmailAddress;

@end
