#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZVariableexpenseGetListV1ResponseMPayload.h"
@protocol EZVariableexpenseGetListV1ResponseMPayload;
@class EZVariableexpenseGetListV1ResponseMPayload;



@protocol EZVariableexpenseGetListV1ResponseAllOf
@end

@interface EZVariableexpenseGetListV1ResponseAllOf : EZObject


@property(nonatomic) EZVariableexpenseGetListV1ResponseMPayload* mPayload;

@end
