#import <Foundation/Foundation.h>
#import "EZObject.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.17
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EZVariableexpenseCreateObjectV1ResponseMPayload.h"
@protocol EZVariableexpenseCreateObjectV1ResponseMPayload;
@class EZVariableexpenseCreateObjectV1ResponseMPayload;



@protocol EZVariableexpenseCreateObjectV1ResponseAllOf
@end

@interface EZVariableexpenseCreateObjectV1ResponseAllOf : EZObject


@property(nonatomic) EZVariableexpenseCreateObjectV1ResponseMPayload* mPayload;

@end
