#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol InscriptiontypeAutocompleteElementResponse
@end

@interface InscriptiontypeAutocompleteElementResponse : Object

/* The unique ID of the Inscriptiontype 
 */
@property(nonatomic) NSNumber* pkiInscriptiontypeID;
/* The name of the Inscriptiontype in the language of the requester 
 */
@property(nonatomic) NSString* sInscriptiontypeNameX;

@end
