#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldEInscriptionnotauthenticatedRemunerationtype.h"
#import "FieldEInscriptionnotauthenticatedResidenceType.h"
#import "FieldEInscriptionnotauthenticatedType.h"
#import "FieldEtInscriptionnotauthenticatedMortgagetype.h"
@protocol FieldEInscriptionnotauthenticatedRemunerationtype;
@class FieldEInscriptionnotauthenticatedRemunerationtype;
@protocol FieldEInscriptionnotauthenticatedResidenceType;
@class FieldEInscriptionnotauthenticatedResidenceType;
@protocol FieldEInscriptionnotauthenticatedType;
@class FieldEInscriptionnotauthenticatedType;
@protocol FieldEtInscriptionnotauthenticatedMortgagetype;
@class FieldEtInscriptionnotauthenticatedMortgagetype;



@protocol InscriptionnotauthenticatedResponse
@end

@interface InscriptionnotauthenticatedResponse : Object

/* The unique ID of the Inscriptionnotauthenticated. 
 */
@property(nonatomic) NSNumber* pkiInscriptionnotauthenticatedID;
/* The unique ID of the Company 
 */
@property(nonatomic) NSNumber* fkiCompanyID;
/* The Name of the Company in the language of the requester [optional]
 */
@property(nonatomic) NSString* sCompanyNameX;
/* The unique ID of the Inscription. 
 */
@property(nonatomic) NSNumber* fkiInscriptionID;
/* The unique ID of the Department 
 */
@property(nonatomic) NSNumber* fkiDepartmentID;
/* The Name of the Department in the language of the requester [optional]
 */
@property(nonatomic) NSString* sDepartmentNameX;
/* The unique ID of the Financialinstitution 
 */
@property(nonatomic) NSNumber* fkiFinancialinstitutionID;
/* The name of the Financialinstitution in the language of the requester [optional]
 */
@property(nonatomic) NSString* sFinancialinstitutionNameX;
/* The unique ID of the Buyercontract 
 */
@property(nonatomic) NSNumber* fkiBuyercontractID;
/* The number of the Buyercontract [optional]
 */
@property(nonatomic) NSString* sBuyercontractContract;
/* The unique ID of the Mortgagesupplier 
 */
@property(nonatomic) NSNumber* fkiMortgagesupplierID;
/* The name of the Mortagesupplier in the language of the requester [optional]
 */
@property(nonatomic) NSString* sMortgagesupplierNameX;
/* The unique ID of the Taxassignment.  Valid values:  |Value|Description| |-|-| |1|No tax| |2|GST| |3|HST (ON)| |4|HST (NB)| |5|HST (NS)| |6|HST (NL)| |7|HST (PE)| |8|GST + QST (QC)| |9|GST + QST (QC) Non-Recoverable| |10|GST + PST (BC)| |11|GST + PST (SK)| |12|GST + RST (MB)| |13|GST + PST (BC) Non-Recoverable| |14|GST + PST (SK) Non-Recoverable| |15|GST + RST (MB) Non-Recoverable| 
 */
@property(nonatomic) NSNumber* fkiTaxassignmentID;
/* The description of the Taxassignment  in the language of the requester [optional]
 */
@property(nonatomic) NSString* sTaxassignmentDescriptionX;
/* The transactiondate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedTransactiondate;
/* The transactiondatereal of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedTransactiondateReal;
/* The depositdate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedDepositdate;

@property(nonatomic) FieldEInscriptionnotauthenticatedType* eInscriptionnotauthenticatedType;
/* The mortgageloan of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dInscriptionnotauthenticatedMortgageloan;

@property(nonatomic) FieldEtInscriptionnotauthenticatedMortgagetype* etInscriptionnotauthenticatedMortgagetype;
/* The transactionprice of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dInscriptionnotauthenticatedTransactionprice;

@property(nonatomic) FieldEInscriptionnotauthenticatedRemunerationtype* eInscriptionnotauthenticatedRemunerationtype;
/* The remuneration of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dInscriptionnotauthenticatedRemuneration;
/* The remunerationsubtotal of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dInscriptionnotauthenticatedRemunerationsubtotal;
/* The remunerationtotal of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dInscriptionnotauthenticatedRemunerationtotal;
/* The cancellationdate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedCancellationdate;
/* The possessiondate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedPossessiondate;
/* The Offer to purchase number 
 */
@property(nonatomic) NSString* sInscriptionnotauthenticatedOffertopurchasenumber;
/* The notaryscheduledate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedNotaryscheduledate;
/* The financingscheduledate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedFinancingscheduledate;
/* Whether the inscriptionnotauthenticated is conditional 
 */
@property(nonatomic) NSNumber* bInscriptionnotauthenticatedConditional;
/* Whether if it's an mortgageisreferenced 
 */
@property(nonatomic) NSNumber* bInscriptionnotauthenticatedMortgageisreferenced;
/* Whether if it's an homeowner 
 */
@property(nonatomic) NSNumber* bInscriptionnotauthenticatedHomeowner;
/* The conditions of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* tInscriptionnotauthenticatedConditions;
/* The conditiondeadlinedate of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dtInscriptionnotauthenticatedConditiondeadlinedate;
/* The order of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSNumber* iInscriptionnotauthenticatedOrder;
/* Whether the inscriptionnotauthenticated is active or not 
 */
@property(nonatomic) NSNumber* bInscriptionnotauthenticatedIsactive;

@property(nonatomic) FieldEInscriptionnotauthenticatedResidenceType* eInscriptionnotauthenticatedResidenceType;
/* The checklistnote of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* tInscriptionnotauthenticatedChecklistnote;
/* The selleronlyretribution of the Inscriptionnotauthenticated 
 */
@property(nonatomic) NSString* dInscriptionnotauthenticatedSelleronlyretribution;
/* Whether the inscriptionnotauthenticated is a draft or not 
 */
@property(nonatomic) NSNumber* bInscriptionnotauthenticatedDraft;

@end
