#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldEInscriptiontempStatus.h"
@protocol FieldEInscriptiontempStatus;
@class FieldEInscriptiontempStatus;



@protocol InscriptiontempListElement
@end

@interface InscriptiontempListElement : Object

/* The unique ID of the Inscriptiontemp 
 */
@property(nonatomic) NSNumber* pkiInscriptiontempID;

@property(nonatomic) FieldEInscriptiontempStatus* eInscriptiontempStatus;
/* The mls of the Inscriptiontemp [optional]
 */
@property(nonatomic) NSString* sInscriptiontempMLS;
/* The description of the Inscriptiontemp 
 */
@property(nonatomic) NSString* sInscriptiontempDescription;
/* Whether the inscriptiontemp is active or not 
 */
@property(nonatomic) NSNumber* bInscriptiontempIsactive;
/* The date and time at which the object was created 
 */
@property(nonatomic) NSString* dtCreatedDate;
/* The date and time at which the object was last modified 
 */
@property(nonatomic) NSString* dtModifiedDate;

@end
