#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol MultilingualEzdoctemplatedocumentName
@end

@interface MultilingualEzdoctemplatedocumentName : Object

/* The name1 of the Ezdoctemplatedocument [optional]
 */
@property(nonatomic) NSString* sEzdoctemplatedocumentName1;
/* The name2 of the Ezdoctemplatedocument [optional]
 */
@property(nonatomic) NSString* sEzdoctemplatedocumentName2;

@end
