#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "FieldEPhoneType.h"
#import "PhoneResponse.h"
@protocol FieldEPhoneType;
@class FieldEPhoneType;
@protocol PhoneResponse;
@class PhoneResponse;



@protocol PhoneResponseCompound
@end

@interface PhoneResponseCompound : PhoneResponse

/* Indicate the phone number is an international phone number. [optional]
 */
@property(nonatomic) NSNumber* bPhoneInternational;

@end
