#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.3
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "SystemconfigurationtypeAutocompleteElementResponse.h"
@protocol SystemconfigurationtypeAutocompleteElementResponse;
@class SystemconfigurationtypeAutocompleteElementResponse;



@protocol SystemconfigurationtypeGetAutocompleteV2ResponseMPayload
@end

@interface SystemconfigurationtypeGetAutocompleteV2ResponseMPayload : Object

/* An array of Systemconfigurationtype autocomplete element response. 
 */
@property(nonatomic) NSArray<SystemconfigurationtypeAutocompleteElementResponse>* aObjSystemconfigurationtype;

@end
