#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "CustomEzmaxcustomeruserResponse.h"
@protocol CustomEzmaxcustomeruserResponse;
@class CustomEzmaxcustomeruserResponse;



@protocol UserGetEzmaxcustomeruserV1ResponseMPayload
@end

@interface UserGetEzmaxcustomeruserV1ResponseMPayload : Object


@property(nonatomic) CustomEzmaxcustomeruserResponse* objEzmaxcustomeruser;

@end
