#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EmailRequest.h"
#import "FieldEUserEzsignaccess.h"
#import "FieldEUserLogintype.h"
#import "FieldEUserType.h"
#import "PhoneRequest.h"
#import "UserRequest.h"
@protocol EmailRequest;
@class EmailRequest;
@protocol FieldEUserEzsignaccess;
@class FieldEUserEzsignaccess;
@protocol FieldEUserLogintype;
@class FieldEUserLogintype;
@protocol FieldEUserType;
@class FieldEUserType;
@protocol PhoneRequest;
@class PhoneRequest;
@protocol UserRequest;
@class UserRequest;



@protocol UserRequestCompound
@end

@interface UserRequestCompound : UserRequest


@end
