#import <Foundation/Foundation.h>
#import "Object.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "EmailRequest.h"
#import "MultilingualUsergroupName.h"
@protocol EmailRequest;
@class EmailRequest;
@protocol MultilingualUsergroupName;
@class MultilingualUsergroupName;



@protocol UsergroupRequest
@end

@interface UsergroupRequest : Object

/* The unique ID of the Usergroup [optional]
 */
@property(nonatomic) NSNumber* pkiUsergroupID;

@property(nonatomic) EmailRequest* objEmail;

@property(nonatomic) MultilingualUsergroupName* objUsergroupName;

@end
