#import <Foundation/Foundation.h>
#import "EzmaxpartnerSubscribeV1Request.h"
#import "EzmaxpartnerSubscribeV1Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ExternalEzmaxpartnerApi: NSObject <Api>

extern NSString* kExternalEzmaxpartnerApiErrorDomain;
extern NSInteger kExternalEzmaxpartnerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Subscribe to an Ezmaxparnerproductstage
/// Subscribe to an Ezmaxparnerproductstage
///
/// @param ezmaxpartnerSubscribeV1Request 
/// 
///  code:200 message:"Successful response"
///
/// @return EzmaxpartnerSubscribeV1Response*
-(NSURLSessionTask*) ezmaxpartnerSubscribeV1WithEzmaxpartnerSubscribeV1Request: (EzmaxpartnerSubscribeV1Request*) ezmaxpartnerSubscribeV1Request
    completionHandler: (void (^)(EzmaxpartnerSubscribeV1Response* output, NSError* error)) handler;



@end
