#import <Foundation/Foundation.h>
#import "EZCommonResponseError.h"
#import "EZGlobalEzmaxcustomerGetConfigurationV1Response.h"
#import "EZApi.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.18
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface EZGlobalEzmaxcustomerApi: NSObject <EZApi>

extern NSString* kEZGlobalEzmaxcustomerApiErrorDomain;
extern NSInteger kEZGlobalEzmaxcustomerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(EZApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get ezmaxcustomer configuration
/// Retrieve the ezmaxcustomer's specific configuration. This will help locate the proper region (ie: sInfrastructureregionCode) and the proper environment (ie: sInfrastructureenvironmenttypeDescription) where the customer's data is stored.
///
/// @param pksEzmaxcustomerCode 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EZGlobalEzmaxcustomerGetConfigurationV1Response*
-(NSURLSessionTask*) globalEzmaxcustomerGetConfigurationV1WithPksEzmaxcustomerCode: (NSString*) pksEzmaxcustomerCode
    completionHandler: (void (^)(EZGlobalEzmaxcustomerGetConfigurationV1Response* output, NSError* error)) handler;



@end
