#import <Foundation/Foundation.h>
#import "EZCommonResponseError.h"
#import "EZEzsigntemplatepackagemembershipCreateObjectV1Request.h"
#import "EZEzsigntemplatepackagemembershipCreateObjectV1Response.h"
#import "EZEzsigntemplatepackagemembershipDeleteObjectV1Response.h"
#import "EZEzsigntemplatepackagemembershipGetObjectV1Response.h"
#import "EZApi.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.1.8
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface EZObjectEzsigntemplatepackagemembershipApi: NSObject <EZApi>

extern NSString* kEZObjectEzsigntemplatepackagemembershipApiErrorDomain;
extern NSInteger kEZObjectEzsigntemplatepackagemembershipApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(EZApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a new Ezsigntemplatepackagemembership
/// The endpoint allows to create one or many elements at once.
///
/// @param ezsigntemplatepackagemembershipCreateObjectV1Request 
/// 
///  code:201 message:"Successful response",
///  code:422 message:"The syntax of the request is valid but the request cannot be completed. Look for detail in body."
///
/// @return EZEzsigntemplatepackagemembershipCreateObjectV1Response*
-(NSURLSessionTask*) ezsigntemplatepackagemembershipCreateObjectV1WithEzsigntemplatepackagemembershipCreateObjectV1Request: (EZEzsigntemplatepackagemembershipCreateObjectV1Request*) ezsigntemplatepackagemembershipCreateObjectV1Request
    completionHandler: (void (^)(EZEzsigntemplatepackagemembershipCreateObjectV1Response* output, NSError* error)) handler;


/// Delete an existing Ezsigntemplatepackagemembership
/// 
///
/// @param pkiEzsigntemplatepackagemembershipID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The element you are trying to work on does not exist"
///
/// @return EZEzsigntemplatepackagemembershipDeleteObjectV1Response*
-(NSURLSessionTask*) ezsigntemplatepackagemembershipDeleteObjectV1WithPkiEzsigntemplatepackagemembershipID: (NSNumber*) pkiEzsigntemplatepackagemembershipID
    completionHandler: (void (^)(EZEzsigntemplatepackagemembershipDeleteObjectV1Response* output, NSError* error)) handler;


/// Retrieve an existing Ezsigntemplatepackagemembership
/// 
///
/// @param pkiEzsigntemplatepackagemembershipID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The element you are trying to work on does not exist"
///
/// @return EZEzsigntemplatepackagemembershipGetObjectV1Response*
-(NSURLSessionTask*) ezsigntemplatepackagemembershipGetObjectV1WithPkiEzsigntemplatepackagemembershipID: (NSNumber*) pkiEzsigntemplatepackagemembershipID
    completionHandler: (void (^)(EZEzsigntemplatepackagemembershipGetObjectV1Response* output, NSError* error)) handler;



@end
