#import <Foundation/Foundation.h>
#import "EZCommonResponseError.h"
#import "EZEzsigntemplatepackagesignermembershipCreateObjectV1Request.h"
#import "EZEzsigntemplatepackagesignermembershipCreateObjectV1Response.h"
#import "EZEzsigntemplatepackagesignermembershipDeleteObjectV1Response.h"
#import "EZEzsigntemplatepackagesignermembershipGetObjectV2Response.h"
#import "EZApi.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface EZObjectEzsigntemplatepackagesignermembershipApi: NSObject <EZApi>

extern NSString* kEZObjectEzsigntemplatepackagesignermembershipApiErrorDomain;
extern NSInteger kEZObjectEzsigntemplatepackagesignermembershipApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(EZApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a new Ezsigntemplatepackagesignermembership
/// The endpoint allows to create one or many elements at once.
///
/// @param ezsigntemplatepackagesignermembershipCreateObjectV1Request 
/// 
///  code:201 message:"Successful response",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body"
///
/// @return EZEzsigntemplatepackagesignermembershipCreateObjectV1Response*
-(NSURLSessionTask*) ezsigntemplatepackagesignermembershipCreateObjectV1WithEzsigntemplatepackagesignermembershipCreateObjectV1Request: (EZEzsigntemplatepackagesignermembershipCreateObjectV1Request*) ezsigntemplatepackagesignermembershipCreateObjectV1Request
    completionHandler: (void (^)(EZEzsigntemplatepackagesignermembershipCreateObjectV1Response* output, NSError* error)) handler;


/// Delete an existing Ezsigntemplatepackagesignermembership
/// 
///
/// @param pkiEzsigntemplatepackagesignermembershipID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EZEzsigntemplatepackagesignermembershipDeleteObjectV1Response*
-(NSURLSessionTask*) ezsigntemplatepackagesignermembershipDeleteObjectV1WithPkiEzsigntemplatepackagesignermembershipID: (NSNumber*) pkiEzsigntemplatepackagesignermembershipID
    completionHandler: (void (^)(EZEzsigntemplatepackagesignermembershipDeleteObjectV1Response* output, NSError* error)) handler;


/// Retrieve an existing Ezsigntemplatepackagesignermembership
/// 
///
/// @param pkiEzsigntemplatepackagesignermembershipID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EZEzsigntemplatepackagesignermembershipGetObjectV2Response*
-(NSURLSessionTask*) ezsigntemplatepackagesignermembershipGetObjectV2WithPkiEzsigntemplatepackagesignermembershipID: (NSNumber*) pkiEzsigntemplatepackagesignermembershipID
    completionHandler: (void (^)(EZEzsigntemplatepackagesignermembershipGetObjectV2Response* output, NSError* error)) handler;



@end
