#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "DisclosureBatchDownloadV1Request.h"
#import "DisclosureGetAttachmentsV1Response.h"
#import "DisclosureImportIntoEDMV1Request.h"
#import "DisclosureImportIntoEDMV1Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectDisclosureApi: NSObject <Api>

extern NSString* kObjectDisclosureApiErrorDomain;
extern NSInteger kObjectDisclosureApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Download multiples attachments from a Disclosure
/// 
///
/// @param pkiDisclosureID 
/// @param disclosureBatchDownloadV1Request 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:406 message:"The URL is valid, but one of the Accept header is not defined or invalid. For example, you set the header \"Accept: application/json\" but the function can only return \"Content-type: image/png\"",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return NSURL*
-(NSURLSessionTask*) disclosureBatchDownloadV1WithPkiDisclosureID: (NSNumber*) pkiDisclosureID
    disclosureBatchDownloadV1Request: (DisclosureBatchDownloadV1Request*) disclosureBatchDownloadV1Request
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Retrieve Disclosure's attachments
/// 
///
/// @param pkiDisclosureID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body."
///
/// @return DisclosureGetAttachmentsV1Response*
-(NSURLSessionTask*) disclosureGetAttachmentsV1WithPkiDisclosureID: (NSNumber*) pkiDisclosureID
    completionHandler: (void (^)(DisclosureGetAttachmentsV1Response* output, NSError* error)) handler;


/// Import attachments into the Disclosure
/// 
///
/// @param pkiDisclosureID 
/// @param disclosureImportIntoEDMV1Request 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body."
///
/// @return DisclosureImportIntoEDMV1Response*
-(NSURLSessionTask*) disclosureImportIntoEDMV1WithPkiDisclosureID: (NSNumber*) pkiDisclosureID
    disclosureImportIntoEDMV1Request: (DisclosureImportIntoEDMV1Request*) disclosureImportIntoEDMV1Request
    completionHandler: (void (^)(DisclosureImportIntoEDMV1Response* output, NSError* error)) handler;



@end
