#import <Foundation/Foundation.h>
#import "AdjustmentBatchDownloadV1Request.h"
#import "AdjustmentGetAttachmentsV1Response.h"
#import "AdjustmentGetCommunicationCountV1Response.h"
#import "AdjustmentGetCommunicationListV1Response.h"
#import "AdjustmentGetCommunicationrecipientsV1Response.h"
#import "AdjustmentGetCommunicationsendersV1Response.h"
#import "AdjustmentImportIntoEDMV1Request.h"
#import "AdjustmentImportIntoEDMV1Response.h"
#import "CommonResponseError.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectAdjustmentApi: NSObject <Api>

extern NSString* kObjectAdjustmentApiErrorDomain;
extern NSInteger kObjectAdjustmentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Download multiples attachments from an Adjustment
/// 
///
/// @param pkiAdjustmentID 
/// @param adjustmentBatchDownloadV1Request 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:406 message:"The URL is valid, but one of the Accept header is not defined or invalid. For example, you set the header \"Accept: application/json\" but the function can only return \"Content-type: image/png\"",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return NSURL*
-(NSURLSessionTask*) adjustmentBatchDownloadV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    adjustmentBatchDownloadV1Request: (AdjustmentBatchDownloadV1Request*) adjustmentBatchDownloadV1Request
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Retrieve Adjustment's attachments
/// 
///
/// @param pkiAdjustmentID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return AdjustmentGetAttachmentsV1Response*
-(NSURLSessionTask*) adjustmentGetAttachmentsV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    completionHandler: (void (^)(AdjustmentGetAttachmentsV1Response* output, NSError* error)) handler;


/// Retrieve Communication count
/// 
///
/// @param pkiAdjustmentID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return AdjustmentGetCommunicationCountV1Response*
-(NSURLSessionTask*) adjustmentGetCommunicationCountV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    completionHandler: (void (^)(AdjustmentGetCommunicationCountV1Response* output, NSError* error)) handler;


/// Retrieve Communication list
/// 
///
/// @param pkiAdjustmentID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return AdjustmentGetCommunicationListV1Response*
-(NSURLSessionTask*) adjustmentGetCommunicationListV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    completionHandler: (void (^)(AdjustmentGetCommunicationListV1Response* output, NSError* error)) handler;


/// Retrieve Communication recipients
/// 
///
/// @param pkiAdjustmentID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return AdjustmentGetCommunicationrecipientsV1Response*
-(NSURLSessionTask*) adjustmentGetCommunicationrecipientsV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    completionHandler: (void (^)(AdjustmentGetCommunicationrecipientsV1Response* output, NSError* error)) handler;


/// Retrieve Communication senders
/// 
///
/// @param pkiAdjustmentID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return AdjustmentGetCommunicationsendersV1Response*
-(NSURLSessionTask*) adjustmentGetCommunicationsendersV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    completionHandler: (void (^)(AdjustmentGetCommunicationsendersV1Response* output, NSError* error)) handler;


/// Import attachments into the Adjustment
/// 
///
/// @param pkiAdjustmentID 
/// @param adjustmentImportIntoEDMV1Request 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body.",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body."
///
/// @return AdjustmentImportIntoEDMV1Response*
-(NSURLSessionTask*) adjustmentImportIntoEDMV1WithPkiAdjustmentID: (NSNumber*) pkiAdjustmentID
    adjustmentImportIntoEDMV1Request: (AdjustmentImportIntoEDMV1Request*) adjustmentImportIntoEDMV1Request
    completionHandler: (void (^)(AdjustmentImportIntoEDMV1Response* output, NSError* error)) handler;



@end
