#import <Foundation/Foundation.h>
#import "ContacttitleGetAutocompleteV2Response.h"
#import "HeaderAcceptLanguage.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.2
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectContacttitleApi: NSObject <Api>

extern NSString* kObjectContacttitleApiErrorDomain;
extern NSInteger kObjectContacttitleApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve Contacttitles and IDs
/// Get the list of Contacttitle to be used in a dropdown or autocomplete control.
///
/// @param sSelector The type of Contacttitles to return
/// @param sQuery Allow to filter the returned results (optional)
/// @param acceptLanguage  (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return ContacttitleGetAutocompleteV2Response*
-(NSURLSessionTask*) contacttitleGetAutocompleteV2WithSSelector: (NSString*) sSelector
    sQuery: (NSString*) sQuery
    acceptLanguage: (HeaderAcceptLanguage) acceptLanguage
    completionHandler: (void (^)(ContacttitleGetAutocompleteV2Response* output, NSError* error)) handler;



@end
