#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "InvoiceGetAttachmentsV1Response.h"
#import "InvoiceGetCommunicationListV1Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectInvoiceApi: NSObject <Api>

extern NSString* kObjectInvoiceApiErrorDomain;
extern NSInteger kObjectInvoiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve Invoice's Attachments
/// 
///
/// @param pkiInvoiceID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return InvoiceGetAttachmentsV1Response*
-(NSURLSessionTask*) invoiceGetAttachmentsV1WithPkiInvoiceID: (NSNumber*) pkiInvoiceID
    completionHandler: (void (^)(InvoiceGetAttachmentsV1Response* output, NSError* error)) handler;


/// Retrieve Communication list
/// 
///
/// @param pkiInvoiceID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return InvoiceGetCommunicationListV1Response*
-(NSURLSessionTask*) invoiceGetCommunicationListV1WithPkiInvoiceID: (NSNumber*) pkiInvoiceID
    completionHandler: (void (^)(InvoiceGetCommunicationListV1Response* output, NSError* error)) handler;



@end
