#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "EzsignbulksendsignermappingCreateObjectV1Request.h"
#import "EzsignbulksendsignermappingCreateObjectV1Response.h"
#import "EzsignbulksendsignermappingDeleteObjectV1Response.h"
#import "EzsignbulksendsignermappingGetObjectV2Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectEzsignbulksendsignermappingApi: NSObject <Api>

extern NSString* kObjectEzsignbulksendsignermappingApiErrorDomain;
extern NSInteger kObjectEzsignbulksendsignermappingApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a new Ezsignbulksendsignermapping
/// The endpoint allows to create one or many elements at once.
///
/// @param ezsignbulksendsignermappingCreateObjectV1Request 
/// 
///  code:201 message:"Successful response"
///
/// @return EzsignbulksendsignermappingCreateObjectV1Response*
-(NSURLSessionTask*) ezsignbulksendsignermappingCreateObjectV1WithEzsignbulksendsignermappingCreateObjectV1Request: (EzsignbulksendsignermappingCreateObjectV1Request*) ezsignbulksendsignermappingCreateObjectV1Request
    completionHandler: (void (^)(EzsignbulksendsignermappingCreateObjectV1Response* output, NSError* error)) handler;


/// Delete an existing Ezsignbulksendsignermapping
/// 
///
/// @param pkiEzsignbulksendsignermappingID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EzsignbulksendsignermappingDeleteObjectV1Response*
-(NSURLSessionTask*) ezsignbulksendsignermappingDeleteObjectV1WithPkiEzsignbulksendsignermappingID: (NSNumber*) pkiEzsignbulksendsignermappingID
    completionHandler: (void (^)(EzsignbulksendsignermappingDeleteObjectV1Response* output, NSError* error)) handler;


/// Retrieve an existing Ezsignbulksendsignermapping
/// 
///
/// @param pkiEzsignbulksendsignermappingID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EzsignbulksendsignermappingGetObjectV2Response*
-(NSURLSessionTask*) ezsignbulksendsignermappingGetObjectV2WithPkiEzsignbulksendsignermappingID: (NSNumber*) pkiEzsignbulksendsignermappingID
    completionHandler: (void (^)(EzsignbulksendsignermappingGetObjectV2Response* output, NSError* error)) handler;



@end
