#import <Foundation/Foundation.h>
#import "BrokertypeGetAutocompleteV2Response.h"
#import "HeaderAcceptLanguage.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectBrokertypeApi: NSObject <Api>

extern NSString* kObjectBrokertypeApiErrorDomain;
extern NSInteger kObjectBrokertypeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve Brokertypes and IDs
/// Get the list of Brokertype to be used in a dropdown or autocomplete control.
///
/// @param sSelector The type of Brokertypes to return
/// @param eFilterActive Specify which results we want to display. (optional) (default to @"Active")
/// @param sQuery Allow to filter the returned results (optional)
/// @param acceptLanguage  (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return BrokertypeGetAutocompleteV2Response*
-(NSURLSessionTask*) brokertypeGetAutocompleteV2WithSSelector: (NSString*) sSelector
    eFilterActive: (NSString*) eFilterActive
    sQuery: (NSString*) sQuery
    acceptLanguage: (HeaderAcceptLanguage) acceptLanguage
    completionHandler: (void (^)(BrokertypeGetAutocompleteV2Response* output, NSError* error)) handler;



@end
