#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "EzsignsignergroupmembershipCreateObjectV1Request.h"
#import "EzsignsignergroupmembershipCreateObjectV1Response.h"
#import "EzsignsignergroupmembershipDeleteObjectV1Response.h"
#import "EzsignsignergroupmembershipGetObjectV2Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectEzsignsignergroupmembershipApi: NSObject <Api>

extern NSString* kObjectEzsignsignergroupmembershipApiErrorDomain;
extern NSInteger kObjectEzsignsignergroupmembershipApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a new Ezsignsignergroupmembership
/// The endpoint allows to create one or many elements at once.
///
/// @param ezsignsignergroupmembershipCreateObjectV1Request 
/// 
///  code:201 message:"Successful response"
///
/// @return EzsignsignergroupmembershipCreateObjectV1Response*
-(NSURLSessionTask*) ezsignsignergroupmembershipCreateObjectV1WithEzsignsignergroupmembershipCreateObjectV1Request: (EzsignsignergroupmembershipCreateObjectV1Request*) ezsignsignergroupmembershipCreateObjectV1Request
    completionHandler: (void (^)(EzsignsignergroupmembershipCreateObjectV1Response* output, NSError* error)) handler;


/// Delete an existing Ezsignsignergroupmembership
/// 
///
/// @param pkiEzsignsignergroupmembershipID The unique ID of the Ezsignsignergroupmembership
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EzsignsignergroupmembershipDeleteObjectV1Response*
-(NSURLSessionTask*) ezsignsignergroupmembershipDeleteObjectV1WithPkiEzsignsignergroupmembershipID: (NSNumber*) pkiEzsignsignergroupmembershipID
    completionHandler: (void (^)(EzsignsignergroupmembershipDeleteObjectV1Response* output, NSError* error)) handler;


/// Retrieve an existing Ezsignsignergroupmembership
/// 
///
/// @param pkiEzsignsignergroupmembershipID The unique ID of the Ezsignsignergroupmembership
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EzsignsignergroupmembershipGetObjectV2Response*
-(NSURLSessionTask*) ezsignsignergroupmembershipGetObjectV2WithPkiEzsignsignergroupmembershipID: (NSNumber*) pkiEzsignsignergroupmembershipID
    completionHandler: (void (^)(EzsignsignergroupmembershipGetObjectV2Response* output, NSError* error)) handler;



@end
