#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "EzsigntemplateglobalannotationGetObjectV2Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectEzsigntemplateglobalannotationApi: NSObject <Api>

extern NSString* kObjectEzsigntemplateglobalannotationApiErrorDomain;
extern NSInteger kObjectEzsigntemplateglobalannotationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve an existing Ezsigntemplateglobalannotation
/// 
///
/// @param pkiEzsigntemplateglobalannotationID The unique ID of the Ezsigntemplateglobalannotation
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return EzsigntemplateglobalannotationGetObjectV2Response*
-(NSURLSessionTask*) ezsigntemplateglobalannotationGetObjectV2WithPkiEzsigntemplateglobalannotationID: (NSNumber*) pkiEzsigntemplateglobalannotationID
    completionHandler: (void (^)(EzsigntemplateglobalannotationGetObjectV2Response* output, NSError* error)) handler;



@end
