#import <Foundation/Foundation.h>
#import "AttachmentDownloadV1Response.h"
#import "CommonResponseError.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectAttachmentApi: NSObject <Api>

extern NSString* kObjectAttachmentApiErrorDomain;
extern NSInteger kObjectAttachmentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve the content
/// Using this endpoint, you can retrieve the content of an attachment.
///
/// @param pkiAttachmentID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body",
///  code:422 message:"The request was syntactically valid but failed because of an interdependance condition. Look for detail about the error in the body"
///
/// @return AttachmentDownloadV1Response*
-(NSURLSessionTask*) attachmentDownloadV1WithPkiAttachmentID: (NSNumber*) pkiAttachmentID
    completionHandler: (void (^)(AttachmentDownloadV1Response* output, NSError* error)) handler;



@end
