#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "RejectedoffertopurchaseGetCommunicationCountV1Response.h"
#import "RejectedoffertopurchaseGetCommunicationListV1Response.h"
#import "RejectedoffertopurchaseGetCommunicationrecipientsV1Response.h"
#import "RejectedoffertopurchaseGetCommunicationsendersV1Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.1
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectRejectedoffertopurchaseApi: NSObject <Api>

extern NSString* kObjectRejectedoffertopurchaseApiErrorDomain;
extern NSInteger kObjectRejectedoffertopurchaseApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve Communication count
/// 
///
/// @param pkiRejectedoffertopurchaseID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return RejectedoffertopurchaseGetCommunicationCountV1Response*
-(NSURLSessionTask*) rejectedoffertopurchaseGetCommunicationCountV1WithPkiRejectedoffertopurchaseID: (NSNumber*) pkiRejectedoffertopurchaseID
    completionHandler: (void (^)(RejectedoffertopurchaseGetCommunicationCountV1Response* output, NSError* error)) handler;


/// Retrieve Communication list
/// 
///
/// @param pkiRejectedoffertopurchaseID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return RejectedoffertopurchaseGetCommunicationListV1Response*
-(NSURLSessionTask*) rejectedoffertopurchaseGetCommunicationListV1WithPkiRejectedoffertopurchaseID: (NSNumber*) pkiRejectedoffertopurchaseID
    completionHandler: (void (^)(RejectedoffertopurchaseGetCommunicationListV1Response* output, NSError* error)) handler;


/// Retrieve Rejectedoffertopurchase's Communicationrecipient
/// 
///
/// @param pkiRejectedoffertopurchaseID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return RejectedoffertopurchaseGetCommunicationrecipientsV1Response*
-(NSURLSessionTask*) rejectedoffertopurchaseGetCommunicationrecipientsV1WithPkiRejectedoffertopurchaseID: (NSNumber*) pkiRejectedoffertopurchaseID
    completionHandler: (void (^)(RejectedoffertopurchaseGetCommunicationrecipientsV1Response* output, NSError* error)) handler;


/// Retrieve Rejectedoffertopurchase's Communicationsender
/// 
///
/// @param pkiRejectedoffertopurchaseID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body"
///
/// @return RejectedoffertopurchaseGetCommunicationsendersV1Response*
-(NSURLSessionTask*) rejectedoffertopurchaseGetCommunicationsendersV1WithPkiRejectedoffertopurchaseID: (NSNumber*) pkiRejectedoffertopurchaseID
    completionHandler: (void (^)(RejectedoffertopurchaseGetCommunicationsendersV1Response* output, NSError* error)) handler;



@end
