#import <Foundation/Foundation.h>
#import "CommonResponseError.h"
#import "NotificationtestGetElementsV2Response.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.3.4
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ObjectNotificationtestApi: NSObject <Api>

extern NSString* kObjectNotificationtestApiErrorDomain;
extern NSInteger kObjectNotificationtestApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Retrieve an existing Notificationtest's Elements
/// 
///
/// @param pkiNotificationtestID 
/// 
///  code:200 message:"Successful response",
///  code:404 message:"The request failed. The element on which you were trying to work does not exists. Look for detail about the error in the body."
///
/// @return NotificationtestGetElementsV2Response*
-(NSURLSessionTask*) notificationtestGetElementsV2WithPkiNotificationtestID: (NSNumber*) pkiNotificationtestID
    completionHandler: (void (^)(NotificationtestGetElementsV2Response* output, NSError* error)) handler;



@end
