#import <Foundation/Foundation.h>
#import "ScimServiceProviderConfig.h"
#import "Api.h"

/**
* eZmax API Definition (Full)
* This API expose all the functionnalities for the eZmax and eZsign applications.
*
* The version of the OpenAPI document: 1.2.0
* Contact: support-api@ezmax.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface ScimServiceProviderConfigApi: NSObject <Api>

extern NSString* kScimServiceProviderConfigApiErrorDomain;
extern NSInteger kScimServiceProviderConfigApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get Service Provider Configuration
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return ScimServiceProviderConfig*
-(NSURLSessionTask*) serviceProviderConfigGetObjectScimV2WithCompletionHandler: 
    (void (^)(ScimServiceProviderConfig* output, NSError* error)) handler;



@end
